/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { PaginatedAttribute } from "../models/index";
import {
	PaginatedAttributeFromJSON,
	PaginatedAttributeToJSON,
} from "../models/index";

export interface AttributesApiGetAttributesRequest {
	id?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

/**
 *
 */
export class AttributesApi extends runtime.BaseAPI {
	/**
	 * Describe the attributes available in the system.  <br><b>id</b> - attribute id.  <br><b>itemsOnPage</b> - items to be displayed on page.  <br><b>pageNo</b> - page number to display.
	 */
	async getAttributesRaw(
		requestParameters: AttributesApiGetAttributesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedAttribute>> {
		const queryParameters: any = {};

		if (requestParameters["id"] != null) {
			queryParameters["id"] = requestParameters["id"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/attributes`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedAttributeFromJSON(jsonValue),
		);
	}

	/**
	 * Describe the attributes available in the system.  <br><b>id</b> - attribute id.  <br><b>itemsOnPage</b> - items to be displayed on page.  <br><b>pageNo</b> - page number to display.
	 */
	async getAttributes(
		requestParameters: AttributesApiGetAttributesRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedAttribute> {
		const response = await this.getAttributesRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}
}
