/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
	Category,
	PaginatedCategory,
	PaginatedProduct,
	PaginatedSimplifiedCategory,
	SimplifiedCategory,
} from "../models/index";
import {
	CategoryFromJSON,
	PaginatedCategoryFromJSON,
	PaginatedProductFromJSON,
	PaginatedSimplifiedCategoryFromJSON,
	SimplifiedCategoryFromJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CategoriesApiGetAncestorsRequest {
	categoryId: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

export interface CategoriesApiGetCategoriesRequest {
	name?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

export interface CategoriesApiGetCategoryByIdRequest {
	categoryId: string;
	deep?: number;
	context?: string;
}

export interface CategoriesApiGetProductsRequest {
	categoryId: string;
	subCategories?: boolean;
	labels?: string;
	name?: string;
	number?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

export interface CategoriesApiScanRequest {
	categoryId?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

/**
 *
 */
export class CategoriesApi extends runtime.BaseAPI {
	/**
	 * Describe categories associated with given category. <br><b>deep</b> - deepness of sub categories to be retrieved. default 10.
	 */
	async getAncestorsRaw(
		requestParameters: CategoriesApiGetAncestorsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<SimplifiedCategory>>> {
		if (requestParameters["categoryId"] == null) {
			throw new runtime.RequiredError(
				"categoryId",
				'Required parameter "categoryId" was null or undefined when calling getAncestors().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories/{categoryId}/ancestors`.replace(
					`{${"categoryId"}}`,
					encodeURIComponent(String(requestParameters["categoryId"])),
				),
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(SimplifiedCategoryFromJSON),
		);
	}

	/**
	 * Describe categories associated with given category. <br><b>deep</b> - deepness of sub categories to be retrieved. default 10.
	 */
	async getAncestors(
		requestParameters: CategoriesApiGetAncestorsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<SimplifiedCategory>> {
		const response = await this.getAncestorsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Describe the root categories available in the system.  <br><b>name</b> - category contains a name  <br><b>itemsOnPage</b> - items to be displayed on page.  <br><b>pageNo</b> - page number to display.
	 */
	async getCategoriesRaw(
		requestParameters: CategoriesApiGetCategoriesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedCategory>> {
		const queryParameters: any = {};

		if (requestParameters["name"] != null) {
			queryParameters["name"] = requestParameters["name"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedCategoryFromJSON(jsonValue),
		);
	}

	/**
	 * Describe the root categories available in the system.  <br><b>name</b> - category contains a name  <br><b>itemsOnPage</b> - items to be displayed on page.  <br><b>pageNo</b> - page number to display.
	 */
	async getCategories(
		requestParameters: CategoriesApiGetCategoriesRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedCategory> {
		const response = await this.getCategoriesRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Describe categories associated with given category. <br><b>deep</b> - deepness of sub categories to be retrieved. default 10.
	 */
	async getCategoryByIdRaw(
		requestParameters: CategoriesApiGetCategoryByIdRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Category>> {
		if (requestParameters["categoryId"] == null) {
			throw new runtime.RequiredError(
				"categoryId",
				'Required parameter "categoryId" was null or undefined when calling getCategoryById().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters["deep"] != null) {
			queryParameters["deep"] = requestParameters["deep"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories/{categoryId}`.replace(
					`{${"categoryId"}}`,
					encodeURIComponent(String(requestParameters["categoryId"])),
				),
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CategoryFromJSON(jsonValue),
		);
	}

	/**
	 * Describe categories associated with given category. <br><b>deep</b> - deepness of sub categories to be retrieved. default 10.
	 */
	async getCategoryById(
		requestParameters: CategoriesApiGetCategoryByIdRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Category> {
		const response = await this.getCategoryByIdRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a list of products for given category. <br><b>subCategories</b> - default false. Set to true provides products for all sub categories. <br><b>withLabels</b> - format \"label1;label2\" a set of labels products should contain. <br><b>name</b> - part of the name contained by the product <br><b>itemsOnPage</b> - items to be displayed on page. <br><b>pageNo</b> - page number to display.
	 */
	async getProductsRaw(
		requestParameters: CategoriesApiGetProductsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedProduct>> {
		if (requestParameters["categoryId"] == null) {
			throw new runtime.RequiredError(
				"categoryId",
				'Required parameter "categoryId" was null or undefined when calling getProducts().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters["subCategories"] != null) {
			queryParameters["subCategories"] = requestParameters["subCategories"];
		}

		if (requestParameters["labels"] != null) {
			queryParameters["labels"] = requestParameters["labels"];
		}

		if (requestParameters["name"] != null) {
			queryParameters["name"] = requestParameters["name"];
		}

		if (requestParameters["number"] != null) {
			queryParameters["number"] = requestParameters["number"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories/{categoryId}/products`.replace(
					`{${"categoryId"}}`,
					encodeURIComponent(String(requestParameters["categoryId"])),
				),
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedProductFromJSON(jsonValue),
		);
	}

	/**
	 * Get a list of products for given category. <br><b>subCategories</b> - default false. Set to true provides products for all sub categories. <br><b>withLabels</b> - format \"label1;label2\" a set of labels products should contain. <br><b>name</b> - part of the name contained by the product <br><b>itemsOnPage</b> - items to be displayed on page. <br><b>pageNo</b> - page number to display.
	 */
	async getProducts(
		requestParameters: CategoriesApiGetProductsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedProduct> {
		const response = await this.getProductsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get paginated flat list of categories: given category and its descendants. CategoryId is optional, if not provided all catalogs are listed.
	 */
	async scanRaw(
		requestParameters: CategoriesApiScanRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedSimplifiedCategory>> {
		const queryParameters: any = {};

		if (requestParameters["categoryId"] != null) {
			queryParameters["categoryId"] = requestParameters["categoryId"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories/scan`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedSimplifiedCategoryFromJSON(jsonValue),
		);
	}

	/**
	 * Get paginated flat list of categories: given category and its descendants. CategoryId is optional, if not provided all catalogs are listed.
	 */
	async scan(
		requestParameters: CategoriesApiScanRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedSimplifiedCategory> {
		const response = await this.scanRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
