/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SegmentContextRequest } from "../models/index";
import { SegmentContextRequestFromJSON } from "../models/index";
import * as runtime from "../runtime";

/**
 *
 */
export class ContextsApi extends runtime.BaseAPI {
	/**
	 * lists currently available publications
	 */
	async getSegmentInfoRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<SegmentContextRequest>>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/contexts`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(SegmentContextRequestFromJSON),
		);
	}

	/**
	 * lists currently available publications
	 */
	async getSegmentInfo(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<SegmentContextRequest>> {
		const response = await this.getSegmentInfoRaw(initOverrides);
		return await response.value();
	}
}
