/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { SegmentContextRequest } from "../models/index";
import {
  SegmentContextRequestFromJSON,
  SegmentContextRequestToJSON,
} from "../models/index";

/**
 *
 */
export class ContextsApi extends runtime.BaseAPI {
  /**
   * lists currently available publications
   */
  async getSegmentInfoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<SegmentContextRequest>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] = await this.configuration.apiKey(
        "x-api-key"
      ); // secured authentication
    }

    const response = await this.request(
      {
        path: `/contexts`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SegmentContextRequestFromJSON)
    );
  }

  /**
   * lists currently available publications
   */
  async getSegmentInfo(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<SegmentContextRequest>> {
    const response = await this.getSegmentInfoRaw(initOverrides);
    return await response.value();
  }
}
