/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	CursorPageProduct,
	CursorQuery,
	FilteringCriteriaRequest,
	PaginatedProduct,
	PapiError,
	Product,
	ProductResults,
	ProductsByIdsRequest,
	ProductsByNumbersRequest,
} from "../models/index";
import {
	CursorPageProductFromJSON,
	CursorPageProductToJSON,
	CursorQueryFromJSON,
	CursorQueryToJSON,
	FilteringCriteriaRequestFromJSON,
	FilteringCriteriaRequestToJSON,
	PaginatedProductFromJSON,
	PaginatedProductToJSON,
	PapiErrorFromJSON,
	PapiErrorToJSON,
	ProductFromJSON,
	ProductToJSON,
	ProductResultsFromJSON,
	ProductResultsToJSON,
	ProductsByIdsRequestFromJSON,
	ProductsByIdsRequestToJSON,
	ProductsByNumbersRequestFromJSON,
	ProductsByNumbersRequestToJSON,
} from "../models/index";

export interface ProductsApiFindProductsRequest {
	filteringCriteriaRequest: FilteringCriteriaRequest;
	sort?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

export interface ProductsApiFindProductsByCursorRequest {
	cursorQuery: CursorQuery;
	context?: string;
}

export interface ProductsApiFindProductsByIdsRequest {
	productsByIdsRequest: ProductsByIdsRequest;
	context?: string;
}

export interface ProductsApiFindProductsByNumbersRequest {
	productsByNumbersRequest: ProductsByNumbersRequest;
	context?: string;
}

export interface ProductsApiGetProductRequest {
	id: string;
	context?: string;
}

export interface ProductsApiGetProducts0Request {
	categoryId: string;
	subCategories?: boolean;
	labels?: string;
	name?: string;
	number?: string;
	itemsOnPage?: number;
	pageNo?: number;
	context?: string;
}

/**
 *
 */
export class ProductsApi extends runtime.BaseAPI {
	/**
	 * Find products in PAPI
	 */
	async findProductsRaw(
		requestParameters: ProductsApiFindProductsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedProduct>> {
		if (requestParameters["filteringCriteriaRequest"] == null) {
			throw new runtime.RequiredError(
				"filteringCriteriaRequest",
				'Required parameter "filteringCriteriaRequest" was null or undefined when calling findProducts().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters["sort"] != null) {
			queryParameters["sort"] = requestParameters["sort"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/products/list`,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: FilteringCriteriaRequestToJSON(
					requestParameters["filteringCriteriaRequest"],
				),
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedProductFromJSON(jsonValue),
		);
	}

	/**
	 * Find products in PAPI
	 */
	async findProducts(
		requestParameters: ProductsApiFindProductsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedProduct> {
		const response = await this.findProductsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 */
	async findProductsByCursorRaw(
		requestParameters: ProductsApiFindProductsByCursorRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CursorPageProduct>> {
		if (requestParameters["cursorQuery"] == null) {
			throw new runtime.RequiredError(
				"cursorQuery",
				'Required parameter "cursorQuery" was null or undefined when calling findProductsByCursor().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/products/cursor/all`,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: CursorQueryToJSON(requestParameters["cursorQuery"]),
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CursorPageProductFromJSON(jsonValue),
		);
	}

	/**
	 */
	async findProductsByCursor(
		requestParameters: ProductsApiFindProductsByCursorRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CursorPageProduct> {
		const response = await this.findProductsByCursorRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Show list of products filtered by ids.
	 */
	async findProductsByIdsRaw(
		requestParameters: ProductsApiFindProductsByIdsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ProductResults>> {
		if (requestParameters["productsByIdsRequest"] == null) {
			throw new runtime.RequiredError(
				"productsByIdsRequest",
				'Required parameter "productsByIdsRequest" was null or undefined when calling findProductsByIds().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/products/by-ids`,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: ProductsByIdsRequestToJSON(
					requestParameters["productsByIdsRequest"],
				),
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ProductResultsFromJSON(jsonValue),
		);
	}

	/**
	 * Show list of products filtered by ids.
	 */
	async findProductsByIds(
		requestParameters: ProductsApiFindProductsByIdsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ProductResults> {
		const response = await this.findProductsByIdsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Show list of products filtered by numbers.
	 */
	async findProductsByNumbersRaw(
		requestParameters: ProductsApiFindProductsByNumbersRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ProductResults>> {
		if (requestParameters["productsByNumbersRequest"] == null) {
			throw new runtime.RequiredError(
				"productsByNumbersRequest",
				'Required parameter "productsByNumbersRequest" was null or undefined when calling findProductsByNumbers().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/products/by-numbers`,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: ProductsByNumbersRequestToJSON(
					requestParameters["productsByNumbersRequest"],
				),
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ProductResultsFromJSON(jsonValue),
		);
	}

	/**
	 * Show list of products filtered by numbers.
	 */
	async findProductsByNumbers(
		requestParameters: ProductsApiFindProductsByNumbersRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ProductResults> {
		const response = await this.findProductsByNumbersRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get the product with given id
	 */
	async getProductRaw(
		requestParameters: ProductsApiGetProductRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Product>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling getProduct().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/products/{id}`.replace(
					`{${"id"}}`,
					encodeURIComponent(String(requestParameters["id"])),
				),
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ProductFromJSON(jsonValue),
		);
	}

	/**
	 * Get the product with given id
	 */
	async getProduct(
		requestParameters: ProductsApiGetProductRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Product> {
		const response = await this.getProductRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a list of products for given category. <br><b>subCategories</b> - default false. Set to true provides products for all sub categories. <br><b>withLabels</b> - format \"label1;label2\" a set of labels products should contain. <br><b>name</b> - part of the name contained by the product <br><b>itemsOnPage</b> - items to be displayed on page. <br><b>pageNo</b> - page number to display.
	 */
	async getProductsRaw(
		requestParameters: ProductsApiGetProducts0Request,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedProduct>> {
		if (requestParameters["categoryId"] == null) {
			throw new runtime.RequiredError(
				"categoryId",
				'Required parameter "categoryId" was null or undefined when calling getProducts().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters["subCategories"] != null) {
			queryParameters["subCategories"] = requestParameters["subCategories"];
		}

		if (requestParameters["labels"] != null) {
			queryParameters["labels"] = requestParameters["labels"];
		}

		if (requestParameters["name"] != null) {
			queryParameters["name"] = requestParameters["name"];
		}

		if (requestParameters["number"] != null) {
			queryParameters["number"] = requestParameters["number"];
		}

		if (requestParameters["itemsOnPage"] != null) {
			queryParameters["itemsOnPage"] = requestParameters["itemsOnPage"];
		}

		if (requestParameters["pageNo"] != null) {
			queryParameters["pageNo"] = requestParameters["pageNo"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/categories/{categoryId}/products`.replace(
					`{${"categoryId"}}`,
					encodeURIComponent(String(requestParameters["categoryId"])),
				),
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			PaginatedProductFromJSON(jsonValue),
		);
	}

	/**
	 * Get a list of products for given category. <br><b>subCategories</b> - default false. Set to true provides products for all sub categories. <br><b>withLabels</b> - format \"label1;label2\" a set of labels products should contain. <br><b>name</b> - part of the name contained by the product <br><b>itemsOnPage</b> - items to be displayed on page. <br><b>pageNo</b> - page number to display.
	 */
	async getProducts(
		requestParameters: ProductsApiGetProducts0Request,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedProduct> {
		const response = await this.getProductsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}
}
