/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { RelationDefinition } from "../models/index";
import {
	RelationDefinitionFromJSON,
	RelationDefinitionToJSON,
} from "../models/index";

export interface RelationsApiGetRelationsRequest {
	context?: string;
}

/**
 *
 */
export class RelationsApi extends runtime.BaseAPI {
	/**
	 * Describe the relations available in the system.
	 */
	async getRelationsRaw(
		requestParameters: RelationsApiGetRelationsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<RelationDefinition>>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/relations`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(RelationDefinitionFromJSON),
		);
	}

	/**
	 * Describe the relations available in the system.
	 */
	async getRelations(
		requestParameters: RelationsApiGetRelationsRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<RelationDefinition>> {
		const response = await this.getRelationsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}
}
