/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RelationDefinition } from "../models/index";
import { RelationDefinitionFromJSON } from "../models/index";
import * as runtime from "../runtime";

export interface RelationsApiGetRelationsRequest {
	context?: string;
}

/**
 *
 */
export class RelationsApi extends runtime.BaseAPI {
	/**
	 * Describe the relations available in the system.
	 */
	async getRelationsRaw(
		requestParameters: RelationsApiGetRelationsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<RelationDefinition>>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["context"] != null) {
			headerParameters["context"] = String(requestParameters["context"]);
		}

		if (this.configuration && this.configuration.apiKey) {
			headerParameters["x-api-key"] =
				await this.configuration.apiKey("x-api-key"); // secured authentication
		}

		const response = await this.request(
			{
				path: `/relations`,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(RelationDefinitionFromJSON),
		);
	}

	/**
	 * Describe the relations available in the system.
	 */
	async getRelations(
		requestParameters: RelationsApiGetRelationsRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<RelationDefinition>> {
		const response = await this.getRelationsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}
}
