/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ColumnAttribute } from "./ColumnAttribute";
import {
	ColumnAttributeFromJSON,
	ColumnAttributeToJSON,
} from "./ColumnAttribute";
import type { DictionaryValue } from "./DictionaryValue";
import {
	DictionaryValueFromJSON,
	DictionaryValueToJSON,
} from "./DictionaryValue";
import type { MatrixAttributeColumn } from "./MatrixAttributeColumn";
import {
	MatrixAttributeColumnFromJSON,
	MatrixAttributeColumnToJSON,
} from "./MatrixAttributeColumn";
import type { SelectValue } from "./SelectValue";
import { SelectValueFromJSON, SelectValueToJSON } from "./SelectValue";

/**
 *
 * @export
 * @interface Attribute
 */
export interface Attribute {
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	unit?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	groupName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	groupNumber?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	dataType?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Attribute
	 */
	valueType?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof Attribute
	 */
	definingAttribute?: boolean;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Attribute
	 */
	values: Array<string>;
	/**
	 *
	 * @type {Array<SelectValue>}
	 * @memberof Attribute
	 */
	select?: Array<SelectValue>;
	/**
	 *
	 * @type {Array<ColumnAttribute>}
	 * @memberof Attribute
	 */
	column?: Array<ColumnAttribute>;
	/**
	 *
	 * @type {Array<MatrixAttributeColumn>}
	 * @memberof Attribute
	 */
	matrix?: Array<MatrixAttributeColumn>;
	/**
	 *
	 * @type {Array<DictionaryValue>}
	 * @memberof Attribute
	 */
	dictionary?: Array<DictionaryValue>;
}

/**
 * Check if a given object implements the Attribute interface.
 */
export function instanceOfAttribute(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("values" in value)) return false;
	return true;
}

export function AttributeFromJSON(json: any): Attribute {
	return AttributeFromJSONTyped(json, false);
}

export function AttributeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): Attribute {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"] == null ? undefined : json["name"],
		number: json["number"] == null ? undefined : json["number"],
		unit: json["unit"] == null ? undefined : json["unit"],
		groupName: json["groupName"] == null ? undefined : json["groupName"],
		groupNumber: json["groupNumber"] == null ? undefined : json["groupNumber"],
		dataType: json["dataType"] == null ? undefined : json["dataType"],
		valueType: json["valueType"] == null ? undefined : json["valueType"],
		definingAttribute:
			json["definingAttribute"] == null ? undefined : json["definingAttribute"],
		values: json["values"],
		select:
			json["select"] == null
				? undefined
				: (json["select"] as Array<any>).map(SelectValueFromJSON),
		column:
			json["column"] == null
				? undefined
				: (json["column"] as Array<any>).map(ColumnAttributeFromJSON),
		matrix:
			json["matrix"] == null
				? undefined
				: (json["matrix"] as Array<any>).map(MatrixAttributeColumnFromJSON),
		dictionary:
			json["dictionary"] == null
				? undefined
				: (json["dictionary"] as Array<any>).map(DictionaryValueFromJSON),
	};
}

export function AttributeToJSON(value?: Attribute | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		number: value["number"],
		unit: value["unit"],
		groupName: value["groupName"],
		groupNumber: value["groupNumber"],
		dataType: value["dataType"],
		valueType: value["valueType"],
		definingAttribute: value["definingAttribute"],
		values: value["values"],
		select:
			value["select"] == null
				? undefined
				: (value["select"] as Array<any>).map(SelectValueToJSON),
		column:
			value["column"] == null
				? undefined
				: (value["column"] as Array<any>).map(ColumnAttributeToJSON),
		matrix:
			value["matrix"] == null
				? undefined
				: (value["matrix"] as Array<any>).map(MatrixAttributeColumnToJSON),
		dictionary:
			value["dictionary"] == null
				? undefined
				: (value["dictionary"] as Array<any>).map(DictionaryValueToJSON),
	};
}
