/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AttributeFilter
 */
export interface AttributeFilter {
  /**
   * Attribute number the product must have.
   * @type {string}
   * @memberof AttributeFilter
   */
  number?: string;
  /**
   * Attribute value the product must have.
   * @type {string}
   * @memberof AttributeFilter
   */
  value?: string;
}

/**
 * Check if a given object implements the AttributeFilter interface.
 */
export function instanceOfAttributeFilter(
  value: object
): value is AttributeFilter {
  return true;
}

export function AttributeFilterFromJSON(json: any): AttributeFilter {
  return AttributeFilterFromJSONTyped(json, false);
}

export function AttributeFilterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttributeFilter {
  if (json == null) {
    return json;
  }
  return {
    number: json["number"] == null ? undefined : json["number"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function AttributeFilterToJSON(json: any): AttributeFilter {
  return AttributeFilterToJSONTyped(json, false);
}

export function AttributeFilterToJSONTyped(
  value?: AttributeFilter | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    number: value["number"],
    value: value["value"],
  };
}
