/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AttributeFilter
 */
export interface AttributeFilter {
	/**
	 * Attribute number the product must have.
	 * @type {string}
	 * @memberof AttributeFilter
	 */
	number?: string;
	/**
	 * Attribute value the product must have.
	 * @type {string}
	 * @memberof AttributeFilter
	 */
	value?: string;
}

/**
 * Check if a given object implements the AttributeFilter interface.
 */
export function instanceOfAttributeFilter(value: object): boolean {
	return true;
}

export function AttributeFilterFromJSON(json: any): AttributeFilter {
	return AttributeFilterFromJSONTyped(json, false);
}

export function AttributeFilterFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): AttributeFilter {
	if (json == null) {
		return json;
	}
	return {
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function AttributeFilterToJSON(value?: AttributeFilter | null): any {
	if (value == null) {
		return value;
	}
	return {
		number: value["number"],
		value: value["value"],
	};
}
