/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ColumnAttributeDefinitionValue
 */
export interface ColumnAttributeDefinitionValue {
  /**
   *
   * @type {string}
   * @memberof ColumnAttributeDefinitionValue
   */
  valueId: string;
  /**
   *
   * @type {string}
   * @memberof ColumnAttributeDefinitionValue
   */
  value?: string;
}

/**
 * Check if a given object implements the ColumnAttributeDefinitionValue interface.
 */
export function instanceOfColumnAttributeDefinitionValue(
  value: object
): value is ColumnAttributeDefinitionValue {
  if (!("valueId" in value) || value["valueId"] === undefined) return false;
  return true;
}

export function ColumnAttributeDefinitionValueFromJSON(
  json: any
): ColumnAttributeDefinitionValue {
  return ColumnAttributeDefinitionValueFromJSONTyped(json, false);
}

export function ColumnAttributeDefinitionValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ColumnAttributeDefinitionValue {
  if (json == null) {
    return json;
  }
  return {
    valueId: json["valueId"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function ColumnAttributeDefinitionValueToJSON(
  json: any
): ColumnAttributeDefinitionValue {
  return ColumnAttributeDefinitionValueToJSONTyped(json, false);
}

export function ColumnAttributeDefinitionValueToJSONTyped(
  value?: ColumnAttributeDefinitionValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    valueId: value["valueId"],
    value: value["value"],
  };
}
