/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ColumnAttribute
 */
export interface ColumnAttribute {
  /**
   *
   * @type {string}
   * @memberof ColumnAttribute
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ColumnAttribute
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ColumnAttribute
   */
  value?: string;
}

/**
 * Check if a given object implements the ColumnAttribute interface.
 */
export function instanceOfColumnAttribute(
  value: object
): value is ColumnAttribute {
  if (!("id" in value) || value["id"] === undefined) return false;
  return true;
}

export function ColumnAttributeFromJSON(json: any): ColumnAttribute {
  return ColumnAttributeFromJSONTyped(json, false);
}

export function ColumnAttributeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ColumnAttribute {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"] == null ? undefined : json["name"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function ColumnAttributeToJSON(json: any): ColumnAttribute {
  return ColumnAttributeToJSONTyped(json, false);
}

export function ColumnAttributeToJSONTyped(
  value?: ColumnAttribute | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    value: value["value"],
  };
}
