/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ColumnAttributeDefinitionValue
 */
export interface ColumnAttributeDefinitionValue {
	/**
	 *
	 * @type {string}
	 * @memberof ColumnAttributeDefinitionValue
	 */
	valueId: string;
	/**
	 *
	 * @type {string}
	 * @memberof ColumnAttributeDefinitionValue
	 */
	value?: string;
}

/**
 * Check if a given object implements the ColumnAttributeDefinitionValue interface.
 */
export function instanceOfColumnAttributeDefinitionValue(
	value: object,
): boolean {
	if (!("valueId" in value)) return false;
	return true;
}

export function ColumnAttributeDefinitionValueFromJSON(
	json: any,
): ColumnAttributeDefinitionValue {
	return ColumnAttributeDefinitionValueFromJSONTyped(json, false);
}

export function ColumnAttributeDefinitionValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ColumnAttributeDefinitionValue {
	if (json == null) {
		return json;
	}
	return {
		valueId: json["valueId"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function ColumnAttributeDefinitionValueToJSON(
	value?: ColumnAttributeDefinitionValue | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		valueId: value["valueId"],
		value: value["value"],
	};
}
