/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ColumnAttribute
 */
export interface ColumnAttribute {
	/**
	 *
	 * @type {string}
	 * @memberof ColumnAttribute
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof ColumnAttribute
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ColumnAttribute
	 */
	value?: string;
}

/**
 * Check if a given object implements the ColumnAttribute interface.
 */
export function instanceOfColumnAttribute(value: object): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function ColumnAttributeFromJSON(json: any): ColumnAttribute {
	return ColumnAttributeFromJSONTyped(json, false);
}

export function ColumnAttributeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ColumnAttribute {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"] == null ? undefined : json["name"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function ColumnAttributeToJSON(value?: ColumnAttribute | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		value: value["value"],
	};
}
