/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CompoundAttributeSubDefinition
 */
export interface CompoundAttributeSubDefinition {
	/**
	 *
	 * @type {string}
	 * @memberof CompoundAttributeSubDefinition
	 */
	id: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof CompoundAttributeSubDefinition
	 */
	isCompound?: boolean;
}

/**
 * Check if a given object implements the CompoundAttributeSubDefinition interface.
 */
export function instanceOfCompoundAttributeSubDefinition(
	value: object,
): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function CompoundAttributeSubDefinitionFromJSON(
	json: any,
): CompoundAttributeSubDefinition {
	return CompoundAttributeSubDefinitionFromJSONTyped(json, false);
}

export function CompoundAttributeSubDefinitionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CompoundAttributeSubDefinition {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		isCompound: json["isCompound"] == null ? undefined : json["isCompound"],
	};
}

export function CompoundAttributeSubDefinitionToJSON(
	value?: CompoundAttributeSubDefinition | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		isCompound: value["isCompound"],
	};
}
