/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompoundAttributeSubDefinition
 */
export interface CompoundAttributeSubDefinition {
	/**
	 *
	 * @type {string}
	 * @memberof CompoundAttributeSubDefinition
	 */
	id: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof CompoundAttributeSubDefinition
	 */
	isCompound?: boolean;
}

/**
 * Check if a given object implements the CompoundAttributeSubDefinition interface.
 */
export function instanceOfCompoundAttributeSubDefinition(
	value: object,
): value is CompoundAttributeSubDefinition {
	if (!("id" in value) || value["id"] === undefined) return false;
	return true;
}

export function CompoundAttributeSubDefinitionFromJSON(
	json: any,
): CompoundAttributeSubDefinition {
	return CompoundAttributeSubDefinitionFromJSONTyped(json, false);
}

export function CompoundAttributeSubDefinitionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CompoundAttributeSubDefinition {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		isCompound: json["isCompound"] == null ? undefined : json["isCompound"],
	};
}

export function CompoundAttributeSubDefinitionToJSON(
	json: any,
): CompoundAttributeSubDefinition {
	return CompoundAttributeSubDefinitionToJSONTyped(json, false);
}

export function CompoundAttributeSubDefinitionToJSONTyped(
	value?: CompoundAttributeSubDefinition | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		isCompound: value["isCompound"],
	};
}
