/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CursorQuery
 */
export interface CursorQuery {
	/**
	 *
	 * @type {string}
	 * @memberof CursorQuery
	 */
	cursor?: string;
	/**
	 *
	 * @type {number}
	 * @memberof CursorQuery
	 */
	limit?: number;
}

/**
 * Check if a given object implements the CursorQuery interface.
 */
export function instanceOfCursorQuery(value: object): boolean {
	return true;
}

export function CursorQueryFromJSON(json: any): CursorQuery {
	return CursorQueryFromJSONTyped(json, false);
}

export function CursorQueryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CursorQuery {
	if (json == null) {
		return json;
	}
	return {
		cursor: json["cursor"] == null ? undefined : json["cursor"],
		limit: json["limit"] == null ? undefined : json["limit"],
	};
}

export function CursorQueryToJSON(value?: CursorQuery | null): any {
	if (value == null) {
		return value;
	}
	return {
		cursor: value["cursor"],
		limit: value["limit"],
	};
}
