/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Product } from "./Product";
import {
  ProductFromJSON,
  ProductFromJSONTyped,
  ProductToJSON,
  ProductToJSONTyped,
} from "./Product";

/**
 *
 * @export
 * @interface CursorPageProduct
 */
export interface CursorPageProduct {
  /**
   *
   * @type {string}
   * @memberof CursorPageProduct
   */
  nextCursor: string;
  /**
   *
   * @type {Array<Product>}
   * @memberof CursorPageProduct
   */
  results: Array<Product>;
}

/**
 * Check if a given object implements the CursorPageProduct interface.
 */
export function instanceOfCursorPageProduct(
  value: object
): value is CursorPageProduct {
  if (!("nextCursor" in value) || value["nextCursor"] === undefined)
    return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function CursorPageProductFromJSON(json: any): CursorPageProduct {
  return CursorPageProductFromJSONTyped(json, false);
}

export function CursorPageProductFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CursorPageProduct {
  if (json == null) {
    return json;
  }
  return {
    nextCursor: json["nextCursor"],
    results: (json["results"] as Array<any>).map(ProductFromJSON),
  };
}

export function CursorPageProductToJSON(json: any): CursorPageProduct {
  return CursorPageProductToJSONTyped(json, false);
}

export function CursorPageProductToJSONTyped(
  value?: CursorPageProduct | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    nextCursor: value["nextCursor"],
    results: (value["results"] as Array<any>).map(ProductToJSON),
  };
}
