/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Product } from "./Product";
import { ProductFromJSON, ProductToJSON } from "./Product";

/**
 *
 * @export
 * @interface CursorPageProduct
 */
export interface CursorPageProduct {
	/**
	 *
	 * @type {string}
	 * @memberof CursorPageProduct
	 */
	nextCursor: string;
	/**
	 *
	 * @type {Array<Product>}
	 * @memberof CursorPageProduct
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the CursorPageProduct interface.
 */
export function instanceOfCursorPageProduct(value: object): boolean {
	if (!("nextCursor" in value)) return false;
	if (!("results" in value)) return false;
	return true;
}

export function CursorPageProductFromJSON(json: any): CursorPageProduct {
	return CursorPageProductFromJSONTyped(json, false);
}

export function CursorPageProductFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CursorPageProduct {
	if (json == null) {
		return json;
	}
	return {
		nextCursor: json["nextCursor"],
		results: (json["results"] as Array<any>).map(ProductFromJSON),
	};
}

export function CursorPageProductToJSON(value?: CursorPageProduct | null): any {
	if (value == null) {
		return value;
	}
	return {
		nextCursor: value["nextCursor"],
		results: (value["results"] as Array<any>).map(ProductToJSON),
	};
}
