/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CursorQuery
 */
export interface CursorQuery {
	/**
	 *
	 * @type {string}
	 * @memberof CursorQuery
	 */
	cursor?: string;
	/**
	 *
	 * @type {number}
	 * @memberof CursorQuery
	 */
	limit?: number;
}

/**
 * Check if a given object implements the CursorQuery interface.
 */
export function instanceOfCursorQuery(value: object): value is CursorQuery {
	return true;
}

export function CursorQueryFromJSON(json: any): CursorQuery {
	return CursorQueryFromJSONTyped(json, false);
}

export function CursorQueryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CursorQuery {
	if (json == null) {
		return json;
	}
	return {
		cursor: json["cursor"] == null ? undefined : json["cursor"],
		limit: json["limit"] == null ? undefined : json["limit"],
	};
}

export function CursorQueryToJSON(json: any): CursorQuery {
	return CursorQueryToJSONTyped(json, false);
}

export function CursorQueryToJSONTyped(
	value?: CursorQuery | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		cursor: value["cursor"],
		limit: value["limit"],
	};
}
