/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DictionaryValue
 */
export interface DictionaryValue {
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	value?: string;
}

/**
 * Check if a given object implements the DictionaryValue interface.
 */
export function instanceOfDictionaryValue(
	value: object,
): value is DictionaryValue {
	if (!("id" in value) || value["id"] === undefined) return false;
	return true;
}

export function DictionaryValueFromJSON(json: any): DictionaryValue {
	return DictionaryValueFromJSONTyped(json, false);
}

export function DictionaryValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DictionaryValue {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function DictionaryValueToJSON(json: any): DictionaryValue {
	return DictionaryValueToJSONTyped(json, false);
}

export function DictionaryValueToJSONTyped(
	value?: DictionaryValue | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		number: value["number"],
		value: value["value"],
	};
}
