/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DictionaryValue
 */
export interface DictionaryValue {
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof DictionaryValue
	 */
	value?: string;
}

/**
 * Check if a given object implements the DictionaryValue interface.
 */
export function instanceOfDictionaryValue(value: object): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function DictionaryValueFromJSON(json: any): DictionaryValue {
	return DictionaryValueFromJSONTyped(json, false);
}

export function DictionaryValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DictionaryValue {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function DictionaryValueToJSON(value?: DictionaryValue | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		number: value["number"],
		value: value["value"],
	};
}
