/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DiffType = {
	Add: "ADD",
	Delete: "DELETE",
	Change: "CHANGE",
} as const;
export type DiffType = (typeof DiffType)[keyof typeof DiffType];

export function instanceOfDiffType(value: any): boolean {
	return Object.values(DiffType).includes(value);
}

export function DiffTypeFromJSON(json: any): DiffType {
	return DiffTypeFromJSONTyped(json, false);
}

export function DiffTypeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DiffType {
	return json as DiffType;
}

export function DiffTypeToJSON(value?: DiffType | null): any {
	return value as any;
}
