/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DiffType } from "./DiffType";
import {
	DiffTypeFromJSON,
	DiffTypeFromJSONTyped,
	DiffTypeToJSON,
	DiffTypeToJSONTyped,
} from "./DiffType";

/**
 *
 * @export
 * @interface DiffResponse
 */
export interface DiffResponse {
	/**
	 *
	 * @type {string}
	 * @memberof DiffResponse
	 */
	id: string;
	/**
	 *
	 * @type {DiffType}
	 * @memberof DiffResponse
	 */
	diffType: DiffType;
}

/**
 * Check if a given object implements the DiffResponse interface.
 */
export function instanceOfDiffResponse(value: object): value is DiffResponse {
	if (!("id" in value) || value["id"] === undefined) return false;
	if (!("diffType" in value) || value["diffType"] === undefined) return false;
	return true;
}

export function DiffResponseFromJSON(json: any): DiffResponse {
	return DiffResponseFromJSONTyped(json, false);
}

export function DiffResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DiffResponse {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		diffType: DiffTypeFromJSON(json["diffType"]),
	};
}

export function DiffResponseToJSON(json: any): DiffResponse {
	return DiffResponseToJSONTyped(json, false);
}

export function DiffResponseToJSONTyped(
	value?: DiffResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		diffType: DiffTypeToJSON(value["diffType"]),
	};
}
