/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiffType } from "./DiffType";
import { DiffTypeFromJSON, DiffTypeToJSON } from "./DiffType";

/**
 *
 * @export
 * @interface DiffResponse
 */
export interface DiffResponse {
	/**
	 *
	 * @type {string}
	 * @memberof DiffResponse
	 */
	id: string;
	/**
	 *
	 * @type {DiffType}
	 * @memberof DiffResponse
	 */
	diffType: DiffType;
}

/**
 * Check if a given object implements the DiffResponse interface.
 */
export function instanceOfDiffResponse(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("diffType" in value)) return false;
	return true;
}

export function DiffResponseFromJSON(json: any): DiffResponse {
	return DiffResponseFromJSONTyped(json, false);
}

export function DiffResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DiffResponse {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		diffType: DiffTypeFromJSON(json["diffType"]),
	};
}

export function DiffResponseToJSON(value?: DiffResponse | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		diffType: DiffTypeToJSON(value["diffType"]),
	};
}
