/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DiffType = {
	Add: "ADD",
	Delete: "DELETE",
	Change: "CHANGE",
} as const;
export type DiffType = (typeof DiffType)[keyof typeof DiffType];

export function instanceOfDiffType(value: any): boolean {
	for (const key in DiffType) {
		if (Object.prototype.hasOwnProperty.call(DiffType, key)) {
			if (DiffType[key as keyof typeof DiffType] === value) {
				return true;
			}
		}
	}
	return false;
}

export function DiffTypeFromJSON(json: any): DiffType {
	return DiffTypeFromJSONTyped(json, false);
}

export function DiffTypeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): DiffType {
	return json as DiffType;
}

export function DiffTypeToJSON(value?: DiffType | null): any {
	return value as any;
}

export function DiffTypeToJSONTyped(
	value: any,
	ignoreDiscriminator: boolean,
): DiffType {
	return value as DiffType;
}
