/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EntityPapiError
 */
export interface EntityPapiError {
	/**
	 *
	 * @type {number}
	 * @memberof EntityPapiError
	 */
	status: number;
	/**
	 *
	 * @type {string}
	 * @memberof EntityPapiError
	 */
	message: string;
	/**
	 *
	 * @type {string}
	 * @memberof EntityPapiError
	 */
	entityId: string;
}

/**
 * Check if a given object implements the EntityPapiError interface.
 */
export function instanceOfEntityPapiError(value: object): boolean {
	if (!("status" in value)) return false;
	if (!("message" in value)) return false;
	if (!("entityId" in value)) return false;
	return true;
}

export function EntityPapiErrorFromJSON(json: any): EntityPapiError {
	return EntityPapiErrorFromJSONTyped(json, false);
}

export function EntityPapiErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): EntityPapiError {
	if (json == null) {
		return json;
	}
	return {
		status: json["status"],
		message: json["message"],
		entityId: json["entityId"],
	};
}

export function EntityPapiErrorToJSON(value?: EntityPapiError | null): any {
	if (value == null) {
		return value;
	}
	return {
		status: value["status"],
		message: value["message"],
		entityId: value["entityId"],
	};
}
