/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityPapiError
 */
export interface EntityPapiError {
  /**
   *
   * @type {number}
   * @memberof EntityPapiError
   */
  status: number;
  /**
   *
   * @type {string}
   * @memberof EntityPapiError
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof EntityPapiError
   */
  entityId: string;
}

/**
 * Check if a given object implements the EntityPapiError interface.
 */
export function instanceOfEntityPapiError(
  value: object
): value is EntityPapiError {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("entityId" in value) || value["entityId"] === undefined) return false;
  return true;
}

export function EntityPapiErrorFromJSON(json: any): EntityPapiError {
  return EntityPapiErrorFromJSONTyped(json, false);
}

export function EntityPapiErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityPapiError {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    message: json["message"],
    entityId: json["entityId"],
  };
}

export function EntityPapiErrorToJSON(json: any): EntityPapiError {
  return EntityPapiErrorToJSONTyped(json, false);
}

export function EntityPapiErrorToJSONTyped(
  value?: EntityPapiError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    message: value["message"],
    entityId: value["entityId"],
  };
}
