/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntitiesPapiError
 */
export interface EntitiesPapiError {
  /**
   *
   * @type {number}
   * @memberof EntitiesPapiError
   */
  status: number;
  /**
   *
   * @type {string}
   * @memberof EntitiesPapiError
   */
  message: string;
  /**
   *
   * @type {Array<string>}
   * @memberof EntitiesPapiError
   */
  entityIds: Array<string>;
}

/**
 * Check if a given object implements the EntitiesPapiError interface.
 */
export function instanceOfEntitiesPapiError(
  value: object
): value is EntitiesPapiError {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("entityIds" in value) || value["entityIds"] === undefined) return false;
  return true;
}

export function EntitiesPapiErrorFromJSON(json: any): EntitiesPapiError {
  return EntitiesPapiErrorFromJSONTyped(json, false);
}

export function EntitiesPapiErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntitiesPapiError {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    message: json["message"],
    entityIds: json["entityIds"],
  };
}

export function EntitiesPapiErrorToJSON(json: any): EntitiesPapiError {
  return EntitiesPapiErrorToJSONTyped(json, false);
}

export function EntitiesPapiErrorToJSONTyped(
  value?: EntitiesPapiError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    message: value["message"],
    entityIds: value["entityIds"],
  };
}
