/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EntitiesPapiError
 */
export interface EntitiesPapiError {
	/**
	 *
	 * @type {number}
	 * @memberof EntitiesPapiError
	 */
	status: number;
	/**
	 *
	 * @type {string}
	 * @memberof EntitiesPapiError
	 */
	message: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof EntitiesPapiError
	 */
	entityIds: Array<string>;
}

/**
 * Check if a given object implements the EntitiesPapiError interface.
 */
export function instanceOfEntitiesPapiError(value: object): boolean {
	if (!("status" in value)) return false;
	if (!("message" in value)) return false;
	if (!("entityIds" in value)) return false;
	return true;
}

export function EntitiesPapiErrorFromJSON(json: any): EntitiesPapiError {
	return EntitiesPapiErrorFromJSONTyped(json, false);
}

export function EntitiesPapiErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): EntitiesPapiError {
	if (json == null) {
		return json;
	}
	return {
		status: json["status"],
		message: json["message"],
		entityIds: json["entityIds"],
	};
}

export function EntitiesPapiErrorToJSON(value?: EntitiesPapiError | null): any {
	if (value == null) {
		return value;
	}
	return {
		status: value["status"],
		message: value["message"],
		entityIds: value["entityIds"],
	};
}
