/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ColumnAttributeDefinitionValue } from "./ColumnAttributeDefinitionValue";
import {
	ColumnAttributeDefinitionValueFromJSON,
	ColumnAttributeDefinitionValueToJSON,
} from "./ColumnAttributeDefinitionValue";
import type { CompoundAttributeSubDefinition } from "./CompoundAttributeSubDefinition";
import {
	CompoundAttributeSubDefinitionFromJSON,
	CompoundAttributeSubDefinitionToJSON,
} from "./CompoundAttributeSubDefinition";
import type { RowAttributeDefinitionValue } from "./RowAttributeDefinitionValue";
import {
	RowAttributeDefinitionValueFromJSON,
	RowAttributeDefinitionValueToJSON,
} from "./RowAttributeDefinitionValue";
import type { ValueAttributeDefinitionValue } from "./ValueAttributeDefinitionValue";
import {
	ValueAttributeDefinitionValueFromJSON,
	ValueAttributeDefinitionValueToJSON,
} from "./ValueAttributeDefinitionValue";

/**
 *
 * @export
 * @interface GroupedAttributeDefinition
 */
export interface GroupedAttributeDefinition {
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	unit?: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	dataType?: string;
	/**
	 *
	 * @type {number}
	 * @memberof GroupedAttributeDefinition
	 */
	sortingOrder: number;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	groupId: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	groupName: string;
	/**
	 *
	 * @type {string}
	 * @memberof GroupedAttributeDefinition
	 */
	groupNumber?: string;
	/**
	 *
	 * @type {Array<ColumnAttributeDefinitionValue>}
	 * @memberof GroupedAttributeDefinition
	 */
	columns?: Array<ColumnAttributeDefinitionValue>;
	/**
	 *
	 * @type {Array<RowAttributeDefinitionValue>}
	 * @memberof GroupedAttributeDefinition
	 */
	rows?: Array<RowAttributeDefinitionValue>;
	/**
	 *
	 * @type {Array<ValueAttributeDefinitionValue>}
	 * @memberof GroupedAttributeDefinition
	 */
	values?: Array<ValueAttributeDefinitionValue>;
	/**
	 *
	 * @type {boolean}
	 * @memberof GroupedAttributeDefinition
	 */
	isCompound?: boolean;
	/**
	 *
	 * @type {Array<CompoundAttributeSubDefinition>}
	 * @memberof GroupedAttributeDefinition
	 */
	subDefinitions?: Array<CompoundAttributeSubDefinition>;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof GroupedAttributeDefinition
	 */
	format?: Array<string>;
	/**
	 *
	 * @type {number}
	 * @memberof GroupedAttributeDefinition
	 */
	order: number;
	/**
	 *
	 * @type {number}
	 * @memberof GroupedAttributeDefinition
	 */
	groupOrder: number;
}

/**
 * Check if a given object implements the GroupedAttributeDefinition interface.
 */
export function instanceOfGroupedAttributeDefinition(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("name" in value)) return false;
	if (!("sortingOrder" in value)) return false;
	if (!("groupId" in value)) return false;
	if (!("groupName" in value)) return false;
	if (!("order" in value)) return false;
	if (!("groupOrder" in value)) return false;
	return true;
}

export function GroupedAttributeDefinitionFromJSON(
	json: any,
): GroupedAttributeDefinition {
	return GroupedAttributeDefinitionFromJSONTyped(json, false);
}

export function GroupedAttributeDefinitionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): GroupedAttributeDefinition {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"],
		number: json["number"] == null ? undefined : json["number"],
		unit: json["unit"] == null ? undefined : json["unit"],
		dataType: json["dataType"] == null ? undefined : json["dataType"],
		sortingOrder: json["sortingOrder"],
		groupId: json["groupId"],
		groupName: json["groupName"],
		groupNumber: json["groupNumber"] == null ? undefined : json["groupNumber"],
		columns:
			json["columns"] == null
				? undefined
				: (json["columns"] as Array<any>).map(
						ColumnAttributeDefinitionValueFromJSON,
					),
		rows:
			json["rows"] == null
				? undefined
				: (json["rows"] as Array<any>).map(RowAttributeDefinitionValueFromJSON),
		values:
			json["values"] == null
				? undefined
				: (json["values"] as Array<any>).map(
						ValueAttributeDefinitionValueFromJSON,
					),
		isCompound: json["isCompound"] == null ? undefined : json["isCompound"],
		subDefinitions:
			json["subDefinitions"] == null
				? undefined
				: (json["subDefinitions"] as Array<any>).map(
						CompoundAttributeSubDefinitionFromJSON,
					),
		format: json["format"] == null ? undefined : json["format"],
		order: json["order"],
		groupOrder: json["groupOrder"],
	};
}

export function GroupedAttributeDefinitionToJSON(
	value?: GroupedAttributeDefinition | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		number: value["number"],
		unit: value["unit"],
		dataType: value["dataType"],
		sortingOrder: value["sortingOrder"],
		groupId: value["groupId"],
		groupName: value["groupName"],
		groupNumber: value["groupNumber"],
		columns:
			value["columns"] == null
				? undefined
				: (value["columns"] as Array<any>).map(
						ColumnAttributeDefinitionValueToJSON,
					),
		rows:
			value["rows"] == null
				? undefined
				: (value["rows"] as Array<any>).map(RowAttributeDefinitionValueToJSON),
		values:
			value["values"] == null
				? undefined
				: (value["values"] as Array<any>).map(
						ValueAttributeDefinitionValueToJSON,
					),
		isCompound: value["isCompound"],
		subDefinitions:
			value["subDefinitions"] == null
				? undefined
				: (value["subDefinitions"] as Array<any>).map(
						CompoundAttributeSubDefinitionToJSON,
					),
		format: value["format"],
		order: value["order"],
		groupOrder: value["groupOrder"],
	};
}
