/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MatrixAttributeRow } from "./MatrixAttributeRow";
import {
	MatrixAttributeRowFromJSON,
	MatrixAttributeRowToJSON,
} from "./MatrixAttributeRow";

/**
 *
 * @export
 * @interface MatrixAttributeColumn
 */
export interface MatrixAttributeColumn {
	/**
	 *
	 * @type {string}
	 * @memberof MatrixAttributeColumn
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof MatrixAttributeColumn
	 */
	name?: string;
	/**
	 *
	 * @type {Array<MatrixAttributeRow>}
	 * @memberof MatrixAttributeColumn
	 */
	rows?: Array<MatrixAttributeRow>;
}

/**
 * Check if a given object implements the MatrixAttributeColumn interface.
 */
export function instanceOfMatrixAttributeColumn(value: object): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function MatrixAttributeColumnFromJSON(
	json: any,
): MatrixAttributeColumn {
	return MatrixAttributeColumnFromJSONTyped(json, false);
}

export function MatrixAttributeColumnFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MatrixAttributeColumn {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"] == null ? undefined : json["name"],
		rows:
			json["rows"] == null
				? undefined
				: (json["rows"] as Array<any>).map(MatrixAttributeRowFromJSON),
	};
}

export function MatrixAttributeColumnToJSON(
	value?: MatrixAttributeColumn | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		rows:
			value["rows"] == null
				? undefined
				: (value["rows"] as Array<any>).map(MatrixAttributeRowToJSON),
	};
}
