/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MatrixAttributeRow
 */
export interface MatrixAttributeRow {
	/**
	 *
	 * @type {string}
	 * @memberof MatrixAttributeRow
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof MatrixAttributeRow
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MatrixAttributeRow
	 */
	value?: string;
}

/**
 * Check if a given object implements the MatrixAttributeRow interface.
 */
export function instanceOfMatrixAttributeRow(value: object): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function MatrixAttributeRowFromJSON(json: any): MatrixAttributeRow {
	return MatrixAttributeRowFromJSONTyped(json, false);
}

export function MatrixAttributeRowFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MatrixAttributeRow {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"] == null ? undefined : json["name"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function MatrixAttributeRowToJSON(
	value?: MatrixAttributeRow | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		value: value["value"],
	};
}
