/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MatrixAttributeRow } from "./MatrixAttributeRow";
import {
  MatrixAttributeRowFromJSON,
  MatrixAttributeRowFromJSONTyped,
  MatrixAttributeRowToJSON,
  MatrixAttributeRowToJSONTyped,
} from "./MatrixAttributeRow";

/**
 *
 * @export
 * @interface MatrixAttributeColumn
 */
export interface MatrixAttributeColumn {
  /**
   *
   * @type {string}
   * @memberof MatrixAttributeColumn
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof MatrixAttributeColumn
   */
  name?: string;
  /**
   *
   * @type {Array<MatrixAttributeRow>}
   * @memberof MatrixAttributeColumn
   */
  rows?: Array<MatrixAttributeRow>;
}

/**
 * Check if a given object implements the MatrixAttributeColumn interface.
 */
export function instanceOfMatrixAttributeColumn(
  value: object
): value is MatrixAttributeColumn {
  if (!("id" in value) || value["id"] === undefined) return false;
  return true;
}

export function MatrixAttributeColumnFromJSON(
  json: any
): MatrixAttributeColumn {
  return MatrixAttributeColumnFromJSONTyped(json, false);
}

export function MatrixAttributeColumnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MatrixAttributeColumn {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"] == null ? undefined : json["name"],
    rows:
      json["rows"] == null
        ? undefined
        : (json["rows"] as Array<any>).map(MatrixAttributeRowFromJSON),
  };
}

export function MatrixAttributeColumnToJSON(json: any): MatrixAttributeColumn {
  return MatrixAttributeColumnToJSONTyped(json, false);
}

export function MatrixAttributeColumnToJSONTyped(
  value?: MatrixAttributeColumn | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    rows:
      value["rows"] == null
        ? undefined
        : (value["rows"] as Array<any>).map(MatrixAttributeRowToJSON),
  };
}
