/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MediaAsset
 */
export interface MediaAsset {
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	downloadUri: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	previewUri: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	fileName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	contentType: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof MediaAsset
	 */
	labels: Array<string>;
	/**
	 *
	 * @type {number}
	 * @memberof MediaAsset
	 */
	createdAt?: number;
	/**
	 *
	 * @type {number}
	 * @memberof MediaAsset
	 */
	updatedAt?: number;
	/**
	 *
	 * @type {string}
	 * @memberof MediaAsset
	 */
	number?: string;
}

/**
 * Check if a given object implements the MediaAsset interface.
 */
export function instanceOfMediaAsset(value: object): boolean {
	if (!("downloadUri" in value)) return false;
	if (!("previewUri" in value)) return false;
	if (!("name" in value)) return false;
	if (!("contentType" in value)) return false;
	if (!("labels" in value)) return false;
	return true;
}

export function MediaAssetFromJSON(json: any): MediaAsset {
	return MediaAssetFromJSONTyped(json, false);
}

export function MediaAssetFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MediaAsset {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"] == null ? undefined : json["id"],
		downloadUri: json["downloadUri"],
		previewUri: json["previewUri"],
		name: json["name"],
		description: json["description"] == null ? undefined : json["description"],
		fileName: json["fileName"] == null ? undefined : json["fileName"],
		contentType: json["contentType"],
		labels: json["labels"],
		createdAt: json["createdAt"] == null ? undefined : json["createdAt"],
		updatedAt: json["updatedAt"] == null ? undefined : json["updatedAt"],
		number: json["number"] == null ? undefined : json["number"],
	};
}

export function MediaAssetToJSON(value?: MediaAsset | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		downloadUri: value["downloadUri"],
		previewUri: value["previewUri"],
		name: value["name"],
		description: value["description"],
		fileName: value["fileName"],
		contentType: value["contentType"],
		labels: value["labels"],
		createdAt: value["createdAt"],
		updatedAt: value["updatedAt"],
		number: value["number"],
	};
}
