/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MetaData
 */
export interface MetaData {
	/**
	 *
	 * @type {string}
	 * @memberof MetaData
	 */
	id: string;
	/**
	 *
	 * @type {any}
	 * @memberof MetaData
	 */
	value: any | null;
}

/**
 * Check if a given object implements the MetaData interface.
 */
export function instanceOfMetaData(value: object): value is MetaData {
	if (!("id" in value) || value["id"] === undefined) return false;
	if (!("value" in value) || value["value"] === undefined) return false;
	return true;
}

export function MetaDataFromJSON(json: any): MetaData {
	return MetaDataFromJSONTyped(json, false);
}

export function MetaDataFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MetaData {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		value: json["value"],
	};
}

export function MetaDataToJSON(json: any): MetaData {
	return MetaDataToJSONTyped(json, false);
}

export function MetaDataToJSONTyped(
	value?: MetaData | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		value: value["value"],
	};
}
