/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MetaData
 */
export interface MetaData {
	/**
	 *
	 * @type {string}
	 * @memberof MetaData
	 */
	id: string;
	/**
	 *
	 * @type {any}
	 * @memberof MetaData
	 */
	value: any | null;
}

/**
 * Check if a given object implements the MetaData interface.
 */
export function instanceOfMetaData(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("value" in value)) return false;
	return true;
}

export function MetaDataFromJSON(json: any): MetaData {
	return MetaDataFromJSONTyped(json, false);
}

export function MetaDataFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MetaData {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		value: json["value"],
	};
}

export function MetaDataToJSON(value?: MetaData | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		value: value["value"],
	};
}
