/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SimplifiedCategory } from "./SimplifiedCategory";
import {
  SimplifiedCategoryFromJSON,
  SimplifiedCategoryFromJSONTyped,
  SimplifiedCategoryToJSON,
  SimplifiedCategoryToJSONTyped,
} from "./SimplifiedCategory";

/**
 *
 * @export
 * @interface PaginatedSimplifiedCategory
 */
export interface PaginatedSimplifiedCategory {
  /**
   *
   * @type {number}
   * @memberof PaginatedSimplifiedCategory
   */
  totalCount: number;
  /**
   *
   * @type {Array<SimplifiedCategory>}
   * @memberof PaginatedSimplifiedCategory
   */
  results: Array<SimplifiedCategory>;
}

/**
 * Check if a given object implements the PaginatedSimplifiedCategory interface.
 */
export function instanceOfPaginatedSimplifiedCategory(
  value: object
): value is PaginatedSimplifiedCategory {
  if (!("totalCount" in value) || value["totalCount"] === undefined)
    return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedSimplifiedCategoryFromJSON(
  json: any
): PaginatedSimplifiedCategory {
  return PaginatedSimplifiedCategoryFromJSONTyped(json, false);
}

export function PaginatedSimplifiedCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedSimplifiedCategory {
  if (json == null) {
    return json;
  }
  return {
    totalCount: json["totalCount"],
    results: (json["results"] as Array<any>).map(SimplifiedCategoryFromJSON),
  };
}

export function PaginatedSimplifiedCategoryToJSON(
  json: any
): PaginatedSimplifiedCategory {
  return PaginatedSimplifiedCategoryToJSONTyped(json, false);
}

export function PaginatedSimplifiedCategoryToJSONTyped(
  value?: PaginatedSimplifiedCategory | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    totalCount: value["totalCount"],
    results: (value["results"] as Array<any>).map(SimplifiedCategoryToJSON),
  };
}
