/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Category } from "./Category";
import { CategoryFromJSON, CategoryToJSON } from "./Category";

/**
 *
 * @export
 * @interface PaginatedCategory
 */
export interface PaginatedCategory {
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedCategory
	 */
	totalCount: number;
	/**
	 *
	 * @type {Array<Category>}
	 * @memberof PaginatedCategory
	 */
	results: Array<Category>;
}

/**
 * Check if a given object implements the PaginatedCategory interface.
 */
export function instanceOfPaginatedCategory(value: object): boolean {
	if (!("totalCount" in value)) return false;
	if (!("results" in value)) return false;
	return true;
}

export function PaginatedCategoryFromJSON(json: any): PaginatedCategory {
	return PaginatedCategoryFromJSONTyped(json, false);
}

export function PaginatedCategoryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PaginatedCategory {
	if (json == null) {
		return json;
	}
	return {
		totalCount: json["totalCount"],
		results: (json["results"] as Array<any>).map(CategoryFromJSON),
	};
}

export function PaginatedCategoryToJSON(value?: PaginatedCategory | null): any {
	if (value == null) {
		return value;
	}
	return {
		totalCount: value["totalCount"],
		results: (value["results"] as Array<any>).map(CategoryToJSON),
	};
}
