/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Product } from "./Product";
import { ProductFromJSON, ProductToJSON } from "./Product";

/**
 *
 * @export
 * @interface PaginatedProduct
 */
export interface PaginatedProduct {
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedProduct
	 */
	totalCount: number;
	/**
	 *
	 * @type {Array<Product>}
	 * @memberof PaginatedProduct
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the PaginatedProduct interface.
 */
export function instanceOfPaginatedProduct(value: object): boolean {
	if (!("totalCount" in value)) return false;
	if (!("results" in value)) return false;
	return true;
}

export function PaginatedProductFromJSON(json: any): PaginatedProduct {
	return PaginatedProductFromJSONTyped(json, false);
}

export function PaginatedProductFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PaginatedProduct {
	if (json == null) {
		return json;
	}
	return {
		totalCount: json["totalCount"],
		results: (json["results"] as Array<any>).map(ProductFromJSON),
	};
}

export function PaginatedProductToJSON(value?: PaginatedProduct | null): any {
	if (value == null) {
		return value;
	}
	return {
		totalCount: value["totalCount"],
		results: (value["results"] as Array<any>).map(ProductToJSON),
	};
}
