/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GroupedAttributeDefinition } from "./GroupedAttributeDefinition";
import {
  GroupedAttributeDefinitionFromJSON,
  GroupedAttributeDefinitionFromJSONTyped,
  GroupedAttributeDefinitionToJSON,
  GroupedAttributeDefinitionToJSONTyped,
} from "./GroupedAttributeDefinition";

/**
 *
 * @export
 * @interface PaginatedAttribute
 */
export interface PaginatedAttribute {
  /**
   *
   * @type {number}
   * @memberof PaginatedAttribute
   */
  totalCount: number;
  /**
   *
   * @type {Array<GroupedAttributeDefinition>}
   * @memberof PaginatedAttribute
   */
  results: Array<GroupedAttributeDefinition>;
}

/**
 * Check if a given object implements the PaginatedAttribute interface.
 */
export function instanceOfPaginatedAttribute(
  value: object
): value is PaginatedAttribute {
  if (!("totalCount" in value) || value["totalCount"] === undefined)
    return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedAttributeFromJSON(json: any): PaginatedAttribute {
  return PaginatedAttributeFromJSONTyped(json, false);
}

export function PaginatedAttributeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedAttribute {
  if (json == null) {
    return json;
  }
  return {
    totalCount: json["totalCount"],
    results: (json["results"] as Array<any>).map(
      GroupedAttributeDefinitionFromJSON
    ),
  };
}

export function PaginatedAttributeToJSON(json: any): PaginatedAttribute {
  return PaginatedAttributeToJSONTyped(json, false);
}

export function PaginatedAttributeToJSONTyped(
  value?: PaginatedAttribute | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    totalCount: value["totalCount"],
    results: (value["results"] as Array<any>).map(
      GroupedAttributeDefinitionToJSON
    ),
  };
}
