/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Product } from "./Product";
import {
	ProductFromJSON,
	ProductFromJSONTyped,
	ProductToJSON,
	ProductToJSONTyped,
} from "./Product";

/**
 *
 * @export
 * @interface PaginatedProduct
 */
export interface PaginatedProduct {
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedProduct
	 */
	totalCount: number;
	/**
	 *
	 * @type {Array<Product>}
	 * @memberof PaginatedProduct
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the PaginatedProduct interface.
 */
export function instanceOfPaginatedProduct(
	value: object,
): value is PaginatedProduct {
	if (!("totalCount" in value) || value["totalCount"] === undefined)
		return false;
	if (!("results" in value) || value["results"] === undefined) return false;
	return true;
}

export function PaginatedProductFromJSON(json: any): PaginatedProduct {
	return PaginatedProductFromJSONTyped(json, false);
}

export function PaginatedProductFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PaginatedProduct {
	if (json == null) {
		return json;
	}
	return {
		totalCount: json["totalCount"],
		results: (json["results"] as Array<any>).map(ProductFromJSON),
	};
}

export function PaginatedProductToJSON(json: any): PaginatedProduct {
	return PaginatedProductToJSONTyped(json, false);
}

export function PaginatedProductToJSONTyped(
	value?: PaginatedProduct | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		totalCount: value["totalCount"],
		results: (value["results"] as Array<any>).map(ProductToJSON),
	};
}
