/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SimplifiedCategory } from "./SimplifiedCategory";
import {
	SimplifiedCategoryFromJSON,
	SimplifiedCategoryToJSON,
} from "./SimplifiedCategory";

/**
 *
 * @export
 * @interface PaginatedSimplifiedCategory
 */
export interface PaginatedSimplifiedCategory {
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedSimplifiedCategory
	 */
	totalCount: number;
	/**
	 *
	 * @type {Array<SimplifiedCategory>}
	 * @memberof PaginatedSimplifiedCategory
	 */
	results: Array<SimplifiedCategory>;
}

/**
 * Check if a given object implements the PaginatedSimplifiedCategory interface.
 */
export function instanceOfPaginatedSimplifiedCategory(value: object): boolean {
	if (!("totalCount" in value)) return false;
	if (!("results" in value)) return false;
	return true;
}

export function PaginatedSimplifiedCategoryFromJSON(
	json: any,
): PaginatedSimplifiedCategory {
	return PaginatedSimplifiedCategoryFromJSONTyped(json, false);
}

export function PaginatedSimplifiedCategoryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PaginatedSimplifiedCategory {
	if (json == null) {
		return json;
	}
	return {
		totalCount: json["totalCount"],
		results: (json["results"] as Array<any>).map(SimplifiedCategoryFromJSON),
	};
}

export function PaginatedSimplifiedCategoryToJSON(
	value?: PaginatedSimplifiedCategory | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		totalCount: value["totalCount"],
		results: (value["results"] as Array<any>).map(SimplifiedCategoryToJSON),
	};
}
