/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Category } from "./Category";
import {
  CategoryFromJSON,
  CategoryFromJSONTyped,
  CategoryToJSON,
  CategoryToJSONTyped,
} from "./Category";

/**
 *
 * @export
 * @interface PaginatedCategory
 */
export interface PaginatedCategory {
  /**
   *
   * @type {number}
   * @memberof PaginatedCategory
   */
  totalCount: number;
  /**
   *
   * @type {Array<Category>}
   * @memberof PaginatedCategory
   */
  results: Array<Category>;
}

/**
 * Check if a given object implements the PaginatedCategory interface.
 */
export function instanceOfPaginatedCategory(
  value: object
): value is PaginatedCategory {
  if (!("totalCount" in value) || value["totalCount"] === undefined)
    return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedCategoryFromJSON(json: any): PaginatedCategory {
  return PaginatedCategoryFromJSONTyped(json, false);
}

export function PaginatedCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedCategory {
  if (json == null) {
    return json;
  }
  return {
    totalCount: json["totalCount"],
    results: (json["results"] as Array<any>).map(CategoryFromJSON),
  };
}

export function PaginatedCategoryToJSON(json: any): PaginatedCategory {
  return PaginatedCategoryToJSONTyped(json, false);
}

export function PaginatedCategoryToJSONTyped(
  value?: PaginatedCategory | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    totalCount: value["totalCount"],
    results: (value["results"] as Array<any>).map(CategoryToJSON),
  };
}
