/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GroupedAttributeDefinition } from "./GroupedAttributeDefinition";
import {
	GroupedAttributeDefinitionFromJSON,
	GroupedAttributeDefinitionToJSON,
} from "./GroupedAttributeDefinition";

/**
 *
 * @export
 * @interface PaginatedAttribute
 */
export interface PaginatedAttribute {
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedAttribute
	 */
	totalCount: number;
	/**
	 *
	 * @type {Array<GroupedAttributeDefinition>}
	 * @memberof PaginatedAttribute
	 */
	results: Array<GroupedAttributeDefinition>;
}

/**
 * Check if a given object implements the PaginatedAttribute interface.
 */
export function instanceOfPaginatedAttribute(value: object): boolean {
	if (!("totalCount" in value)) return false;
	if (!("results" in value)) return false;
	return true;
}

export function PaginatedAttributeFromJSON(json: any): PaginatedAttribute {
	return PaginatedAttributeFromJSONTyped(json, false);
}

export function PaginatedAttributeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PaginatedAttribute {
	if (json == null) {
		return json;
	}
	return {
		totalCount: json["totalCount"],
		results: (json["results"] as Array<any>).map(
			GroupedAttributeDefinitionFromJSON,
		),
	};
}

export function PaginatedAttributeToJSON(
	value?: PaginatedAttribute | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		totalCount: value["totalCount"],
		results: (value["results"] as Array<any>).map(
			GroupedAttributeDefinitionToJSON,
		),
	};
}
