/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StatusPapiError } from "./StatusPapiError";
import {
	StatusPapiErrorFromJSON,
	StatusPapiErrorFromJSONTyped,
	StatusPapiErrorToJSON,
	StatusPapiErrorToJSONTyped,
} from "./StatusPapiError";
import type { EntitiesPapiError } from "./EntitiesPapiError";
import {
	EntitiesPapiErrorFromJSON,
	EntitiesPapiErrorFromJSONTyped,
	EntitiesPapiErrorToJSON,
	EntitiesPapiErrorToJSONTyped,
} from "./EntitiesPapiError";
import type { EntityPapiError } from "./EntityPapiError";
import {
	EntityPapiErrorFromJSON,
	EntityPapiErrorFromJSONTyped,
	EntityPapiErrorToJSON,
	EntityPapiErrorToJSONTyped,
} from "./EntityPapiError";

/**
 *
 * @export
 * @interface PapiError
 */
export interface PapiError {
	/**
	 *
	 * @type {number}
	 * @memberof PapiError
	 */
	status: number;
	/**
	 *
	 * @type {string}
	 * @memberof PapiError
	 */
	message: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof PapiError
	 */
	entityIds: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof PapiError
	 */
	entityId: string;
}

/**
 * Check if a given object implements the PapiError interface.
 */
export function instanceOfPapiError(value: object): value is PapiError {
	if (!("status" in value) || value["status"] === undefined) return false;
	if (!("message" in value) || value["message"] === undefined) return false;
	if (!("entityIds" in value) || value["entityIds"] === undefined) return false;
	if (!("entityId" in value) || value["entityId"] === undefined) return false;
	return true;
}

export function PapiErrorFromJSON(json: any): PapiError {
	return PapiErrorFromJSONTyped(json, false);
}

export function PapiErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PapiError {
	if (json == null) {
		return json;
	}
	return {
		status: json["status"],
		message: json["message"],
		entityIds: json["entityIds"],
		entityId: json["entityId"],
	};
}

export function PapiErrorToJSON(json: any): PapiError {
	return PapiErrorToJSONTyped(json, false);
}

export function PapiErrorToJSONTyped(
	value?: PapiError | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		status: value["status"],
		message: value["message"],
		entityIds: value["entityIds"],
		entityId: value["entityId"],
	};
}
