/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PapiError
 */
export interface PapiError {
	/**
	 *
	 * @type {number}
	 * @memberof PapiError
	 */
	status: number;
	/**
	 *
	 * @type {string}
	 * @memberof PapiError
	 */
	message: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof PapiError
	 */
	entityIds: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof PapiError
	 */
	entityId: string;
}

/**
 * Check if a given object implements the PapiError interface.
 */
export function instanceOfPapiError(value: object): boolean {
	if (!("status" in value)) return false;
	if (!("message" in value)) return false;
	if (!("entityIds" in value)) return false;
	if (!("entityId" in value)) return false;
	return true;
}

export function PapiErrorFromJSON(json: any): PapiError {
	return PapiErrorFromJSONTyped(json, false);
}

export function PapiErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PapiError {
	if (json == null) {
		return json;
	}
	return {
		status: json["status"],
		message: json["message"],
		entityIds: json["entityIds"],
		entityId: json["entityId"],
	};
}

export function PapiErrorToJSON(value?: PapiError | null): any {
	if (value == null) {
		return value;
	}
	return {
		status: value["status"],
		message: value["message"],
		entityIds: value["entityIds"],
		entityId: value["entityId"],
	};
}
