/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProductsByNumbersRequest
 */
export interface ProductsByNumbersRequest {
	/**
	 * Product numbers to be returned.
	 * @type {Array<string>}
	 * @memberof ProductsByNumbersRequest
	 */
	numbers: Array<string>;
}

/**
 * Check if a given object implements the ProductsByNumbersRequest interface.
 */
export function instanceOfProductsByNumbersRequest(value: object): boolean {
	if (!("numbers" in value)) return false;
	return true;
}

export function ProductsByNumbersRequestFromJSON(
	json: any,
): ProductsByNumbersRequest {
	return ProductsByNumbersRequestFromJSONTyped(json, false);
}

export function ProductsByNumbersRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductsByNumbersRequest {
	if (json == null) {
		return json;
	}
	return {
		numbers: json["numbers"],
	};
}

export function ProductsByNumbersRequestToJSON(
	value?: ProductsByNumbersRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		numbers: value["numbers"],
	};
}
