/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RelationDirection } from "./RelationDirection";
import {
	RelationDirectionFromJSON,
	RelationDirectionFromJSONTyped,
	RelationDirectionToJSON,
	RelationDirectionToJSONTyped,
} from "./RelationDirection";

/**
 *
 * @export
 * @interface ProductRelation
 */
export interface ProductRelation {
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	productId: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof ProductRelation
	 */
	reverse?: boolean;
	/**
	 *
	 * @type {RelationDirection}
	 * @memberof ProductRelation
	 */
	direction: RelationDirection;
}

/**
 * Check if a given object implements the ProductRelation interface.
 */
export function instanceOfProductRelation(
	value: object,
): value is ProductRelation {
	if (!("id" in value) || value["id"] === undefined) return false;
	if (!("name" in value) || value["name"] === undefined) return false;
	if (!("productId" in value) || value["productId"] === undefined) return false;
	if (!("direction" in value) || value["direction"] === undefined) return false;
	return true;
}

export function ProductRelationFromJSON(json: any): ProductRelation {
	return ProductRelationFromJSONTyped(json, false);
}

export function ProductRelationFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductRelation {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"],
		number: json["number"] == null ? undefined : json["number"],
		productId: json["productId"],
		reverse: json["reverse"] == null ? undefined : json["reverse"],
		direction: RelationDirectionFromJSON(json["direction"]),
	};
}

export function ProductRelationToJSON(json: any): ProductRelation {
	return ProductRelationToJSONTyped(json, false);
}

export function ProductRelationToJSONTyped(
	value?: ProductRelation | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		name: value["name"],
		number: value["number"],
		productId: value["productId"],
		reverse: value["reverse"],
		direction: RelationDirectionToJSON(value["direction"]),
	};
}
