/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProductsByNumbersRequest
 */
export interface ProductsByNumbersRequest {
  /**
   * Product numbers to be returned.
   * @type {Array<string>}
   * @memberof ProductsByNumbersRequest
   */
  numbers: Array<string>;
}

/**
 * Check if a given object implements the ProductsByNumbersRequest interface.
 */
export function instanceOfProductsByNumbersRequest(
  value: object
): value is ProductsByNumbersRequest {
  if (!("numbers" in value) || value["numbers"] === undefined) return false;
  return true;
}

export function ProductsByNumbersRequestFromJSON(
  json: any
): ProductsByNumbersRequest {
  return ProductsByNumbersRequestFromJSONTyped(json, false);
}

export function ProductsByNumbersRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProductsByNumbersRequest {
  if (json == null) {
    return json;
  }
  return {
    numbers: json["numbers"],
  };
}

export function ProductsByNumbersRequestToJSON(
  json: any
): ProductsByNumbersRequest {
  return ProductsByNumbersRequestToJSONTyped(json, false);
}

export function ProductsByNumbersRequestToJSONTyped(
  value?: ProductsByNumbersRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    numbers: value["numbers"],
  };
}
