/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ProductType = {
	Bundle: "BUNDLE",
	Group: "GROUP",
	Single: "SINGLE",
	Variant: "VARIANT",
} as const;
export type ProductType = (typeof ProductType)[keyof typeof ProductType];

export function instanceOfProductType(value: any): boolean {
	for (const key in ProductType) {
		if (Object.prototype.hasOwnProperty.call(ProductType, key)) {
			if (ProductType[key as keyof typeof ProductType] === value) {
				return true;
			}
		}
	}
	return false;
}

export function ProductTypeFromJSON(json: any): ProductType {
	return ProductTypeFromJSONTyped(json, false);
}

export function ProductTypeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductType {
	return json as ProductType;
}

export function ProductTypeToJSON(value?: ProductType | null): any {
	return value as any;
}

export function ProductTypeToJSONTyped(
	value: any,
	ignoreDiscriminator: boolean,
): ProductType {
	return value as ProductType;
}
