/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProductBundle
 */
export interface ProductBundle {
	/**
	 *
	 * @type {string}
	 * @memberof ProductBundle
	 */
	productId: string;
	/**
	 *
	 * @type {number}
	 * @memberof ProductBundle
	 */
	quantity: number;
}

/**
 * Check if a given object implements the ProductBundle interface.
 */
export function instanceOfProductBundle(value: object): value is ProductBundle {
	if (!("productId" in value) || value["productId"] === undefined) return false;
	if (!("quantity" in value) || value["quantity"] === undefined) return false;
	return true;
}

export function ProductBundleFromJSON(json: any): ProductBundle {
	return ProductBundleFromJSONTyped(json, false);
}

export function ProductBundleFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductBundle {
	if (json == null) {
		return json;
	}
	return {
		productId: json["productId"],
		quantity: json["quantity"],
	};
}

export function ProductBundleToJSON(json: any): ProductBundle {
	return ProductBundleToJSONTyped(json, false);
}

export function ProductBundleToJSONTyped(
	value?: ProductBundle | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		productId: value["productId"],
		quantity: value["quantity"],
	};
}
