/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RelationDirection } from "./RelationDirection";
import {
	RelationDirectionFromJSON,
	RelationDirectionToJSON,
} from "./RelationDirection";

/**
 *
 * @export
 * @interface ProductRelation
 */
export interface ProductRelation {
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProductRelation
	 */
	productId: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof ProductRelation
	 */
	reverse?: boolean;
	/**
	 *
	 * @type {RelationDirection}
	 * @memberof ProductRelation
	 */
	direction: RelationDirection;
}

/**
 * Check if a given object implements the ProductRelation interface.
 */
export function instanceOfProductRelation(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("name" in value)) return false;
	if (!("productId" in value)) return false;
	if (!("direction" in value)) return false;
	return true;
}

export function ProductRelationFromJSON(json: any): ProductRelation {
	return ProductRelationFromJSONTyped(json, false);
}

export function ProductRelationFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductRelation {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		name: json["name"],
		number: json["number"] == null ? undefined : json["number"],
		productId: json["productId"],
		reverse: json["reverse"] == null ? undefined : json["reverse"],
		direction: RelationDirectionFromJSON(json["direction"]),
	};
}

export function ProductRelationToJSON(value?: ProductRelation | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		name: value["name"],
		number: value["number"],
		productId: value["productId"],
		reverse: value["reverse"],
		direction: RelationDirectionToJSON(value["direction"]),
	};
}
