/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RelatedProductsRelationSortingOrderSource } from "./RelatedProductsRelationSortingOrderSource";
import {
  RelatedProductsRelationSortingOrderSourceFromJSON,
  RelatedProductsRelationSortingOrderSourceFromJSONTyped,
  RelatedProductsRelationSortingOrderSourceToJSON,
  RelatedProductsRelationSortingOrderSourceToJSONTyped,
} from "./RelatedProductsRelationSortingOrderSource";
import type { Attribute } from "./Attribute";
import {
  AttributeFromJSON,
  AttributeFromJSONTyped,
  AttributeToJSON,
  AttributeToJSONTyped,
} from "./Attribute";
import type { MetaData } from "./MetaData";
import {
  MetaDataFromJSON,
  MetaDataFromJSONTyped,
  MetaDataToJSON,
  MetaDataToJSONTyped,
} from "./MetaData";
import type { ProductBundle } from "./ProductBundle";
import {
  ProductBundleFromJSON,
  ProductBundleFromJSONTyped,
  ProductBundleToJSON,
  ProductBundleToJSONTyped,
} from "./ProductBundle";
import type { ProductType } from "./ProductType";
import {
  ProductTypeFromJSON,
  ProductTypeFromJSONTyped,
  ProductTypeToJSON,
  ProductTypeToJSONTyped,
} from "./ProductType";
import type { ProductMediaAsset } from "./ProductMediaAsset";
import {
  ProductMediaAssetFromJSON,
  ProductMediaAssetFromJSONTyped,
  ProductMediaAssetToJSON,
  ProductMediaAssetToJSONTyped,
} from "./ProductMediaAsset";
import type { ProductRelation } from "./ProductRelation";
import {
  ProductRelationFromJSON,
  ProductRelationFromJSONTyped,
  ProductRelationToJSON,
  ProductRelationToJSONTyped,
} from "./ProductRelation";

/**
 *
 * @export
 * @interface Product
 */
export interface Product {
  /**
   * An identifier randomly generated by PIM. ID is unique across all products.
   * @type {string}
   * @memberof Product
   */
  id: string;
  /**
   *
   * @type {ProductType}
   * @memberof Product
   */
  type: ProductType;
  /**
   * Name describe the product. It is not unique across all products.
   * @type {string}
   * @memberof Product
   */
  name: string;
  /**
   * Number is another type of product identifier. It is unique across all products.
   * @type {string}
   * @memberof Product
   */
  number: string;
  /**
   * Description is a field where we put more information about product.
   * @type {string}
   * @memberof Product
   */
  description?: string;
  /**
   * This field inform which attributes have been selected for a product.
   * @type {Array<Attribute>}
   * @memberof Product
   */
  attributes?: Array<Attribute>;
  /**
   * This field inform which media assets have been assigned for a product.
   * @type {Array<ProductMediaAsset>}
   * @memberof Product
   */
  media?: Array<ProductMediaAsset>;
  /**
   * This field inform which labels have been added for a product.
   * @type {Array<string>}
   * @memberof Product
   */
  labels?: Array<string>;
  /**
   * This field inform to which categories, product has been assigned.
   * @type {Array<string>}
   * @memberof Product
   */
  categories?: Array<string>;
  /**
   * This field inform about relations between products.
   * @type {Array<ProductRelation>}
   * @memberof Product
   */
  relations?: Array<ProductRelation>;
  /**
   * This field describe product's metadata.
   * @type {Array<MetaData>}
   * @memberof Product
   */
  metadata?: Array<MetaData>;
  /**
   * Inform when product was last time updated.
   * @type {number}
   * @memberof Product
   */
  lastUpdate?: number;
  /**
   * Inform when product was created.
   * @type {number}
   * @memberof Product
   */
  createDate?: number;
  /**
   * This field inform bundles assigned to product.
   * @type {Array<ProductBundle>}
   * @memberof Product
   */
  bundles?: Array<ProductBundle>;
  /**
   * This field inform about variants added to product.
   * @type {Array<string>}
   * @memberof Product
   */
  variants?: Array<string>;
  /**
   * This field inform about variant parent identifier for product.
   * @type {string}
   * @memberof Product
   */
  variantParentId?: string;
  /**
   *
   * @type {RelatedProductsRelationSortingOrderSource}
   * @memberof Product
   */
  relatedProductsRelationSortingOrderSource?: RelatedProductsRelationSortingOrderSource;
  /**
   * Describe identifier of publish information.
   * @type {string}
   * @memberof Product
   */
  publishInfoId?: string;
  /**
   * Inform about context identifier for published product.
   * @type {string}
   * @memberof Product
   */
  contextId?: string;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("number" in value) || value["number"] === undefined) return false;
  return true;
}

export function ProductFromJSON(json: any): Product {
  return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Product {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    type: ProductTypeFromJSON(json["type"]),
    name: json["name"],
    number: json["number"],
    description: json["description"] == null ? undefined : json["description"],
    attributes:
      json["attributes"] == null
        ? undefined
        : (json["attributes"] as Array<any>).map(AttributeFromJSON),
    media:
      json["media"] == null
        ? undefined
        : (json["media"] as Array<any>).map(ProductMediaAssetFromJSON),
    labels: json["labels"] == null ? undefined : json["labels"],
    categories: json["categories"] == null ? undefined : json["categories"],
    relations:
      json["relations"] == null
        ? undefined
        : (json["relations"] as Array<any>).map(ProductRelationFromJSON),
    metadata:
      json["metadata"] == null
        ? undefined
        : (json["metadata"] as Array<any>).map(MetaDataFromJSON),
    lastUpdate: json["lastUpdate"] == null ? undefined : json["lastUpdate"],
    createDate: json["createDate"] == null ? undefined : json["createDate"],
    bundles:
      json["bundles"] == null
        ? undefined
        : (json["bundles"] as Array<any>).map(ProductBundleFromJSON),
    variants: json["variants"] == null ? undefined : json["variants"],
    variantParentId:
      json["variantParentId"] == null ? undefined : json["variantParentId"],
    relatedProductsRelationSortingOrderSource:
      json["relatedProductsRelationSortingOrderSource"] == null
        ? undefined
        : RelatedProductsRelationSortingOrderSourceFromJSON(
            json["relatedProductsRelationSortingOrderSource"]
          ),
    publishInfoId:
      json["publishInfoId"] == null ? undefined : json["publishInfoId"],
    contextId: json["contextId"] == null ? undefined : json["contextId"],
  };
}

export function ProductToJSON(json: any): Product {
  return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(
  value?: Product | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    type: ProductTypeToJSON(value["type"]),
    name: value["name"],
    number: value["number"],
    description: value["description"],
    attributes:
      value["attributes"] == null
        ? undefined
        : (value["attributes"] as Array<any>).map(AttributeToJSON),
    media:
      value["media"] == null
        ? undefined
        : (value["media"] as Array<any>).map(ProductMediaAssetToJSON),
    labels: value["labels"],
    categories: value["categories"],
    relations:
      value["relations"] == null
        ? undefined
        : (value["relations"] as Array<any>).map(ProductRelationToJSON),
    metadata:
      value["metadata"] == null
        ? undefined
        : (value["metadata"] as Array<any>).map(MetaDataToJSON),
    lastUpdate: value["lastUpdate"],
    createDate: value["createDate"],
    bundles:
      value["bundles"] == null
        ? undefined
        : (value["bundles"] as Array<any>).map(ProductBundleToJSON),
    variants: value["variants"],
    variantParentId: value["variantParentId"],
    relatedProductsRelationSortingOrderSource:
      RelatedProductsRelationSortingOrderSourceToJSON(
        value["relatedProductsRelationSortingOrderSource"]
      ),
    publishInfoId: value["publishInfoId"],
    contextId: value["contextId"],
  };
}
