/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProductsByIdsRequest
 */
export interface ProductsByIdsRequest {
	/**
	 * Product ids returned entries must be matched to.
	 * @type {Array<string>}
	 * @memberof ProductsByIdsRequest
	 */
	ids: Array<string>;
}

/**
 * Check if a given object implements the ProductsByIdsRequest interface.
 */
export function instanceOfProductsByIdsRequest(value: object): boolean {
	if (!("ids" in value)) return false;
	return true;
}

export function ProductsByIdsRequestFromJSON(json: any): ProductsByIdsRequest {
	return ProductsByIdsRequestFromJSONTyped(json, false);
}

export function ProductsByIdsRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductsByIdsRequest {
	if (json == null) {
		return json;
	}
	return {
		ids: json["ids"],
	};
}

export function ProductsByIdsRequestToJSON(
	value?: ProductsByIdsRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		ids: value["ids"],
	};
}
