/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProductsByIdsRequest
 */
export interface ProductsByIdsRequest {
	/**
	 * Product ids returned entries must be matched to.
	 * @type {Array<string>}
	 * @memberof ProductsByIdsRequest
	 */
	ids: Array<string>;
}

/**
 * Check if a given object implements the ProductsByIdsRequest interface.
 */
export function instanceOfProductsByIdsRequest(
	value: object,
): value is ProductsByIdsRequest {
	if (!("ids" in value) || value["ids"] === undefined) return false;
	return true;
}

export function ProductsByIdsRequestFromJSON(json: any): ProductsByIdsRequest {
	return ProductsByIdsRequestFromJSONTyped(json, false);
}

export function ProductsByIdsRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductsByIdsRequest {
	if (json == null) {
		return json;
	}
	return {
		ids: json["ids"],
	};
}

export function ProductsByIdsRequestToJSON(json: any): ProductsByIdsRequest {
	return ProductsByIdsRequestToJSONTyped(json, false);
}

export function ProductsByIdsRequestToJSONTyped(
	value?: ProductsByIdsRequest | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		ids: value["ids"],
	};
}
