/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssetAttribute } from "./AssetAttribute";
import {
  AssetAttributeFromJSON,
  AssetAttributeFromJSONTyped,
  AssetAttributeToJSON,
  AssetAttributeToJSONTyped,
} from "./AssetAttribute";

/**
 *
 * @export
 * @interface ProductMediaAsset
 */
export interface ProductMediaAsset {
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  downloadUri: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  previewUri: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  fileName?: string;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  contentType: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductMediaAsset
   */
  labels: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ProductMediaAsset
   */
  createdAt?: number;
  /**
   *
   * @type {number}
   * @memberof ProductMediaAsset
   */
  updatedAt?: number;
  /**
   *
   * @type {string}
   * @memberof ProductMediaAsset
   */
  number?: string;
  /**
   *
   * @type {Array<AssetAttribute>}
   * @memberof ProductMediaAsset
   */
  attributes?: Array<AssetAttribute>;
}

/**
 * Check if a given object implements the ProductMediaAsset interface.
 */
export function instanceOfProductMediaAsset(
  value: object
): value is ProductMediaAsset {
  if (!("downloadUri" in value) || value["downloadUri"] === undefined)
    return false;
  if (!("previewUri" in value) || value["previewUri"] === undefined)
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("contentType" in value) || value["contentType"] === undefined)
    return false;
  if (!("labels" in value) || value["labels"] === undefined) return false;
  return true;
}

export function ProductMediaAssetFromJSON(json: any): ProductMediaAsset {
  return ProductMediaAssetFromJSONTyped(json, false);
}

export function ProductMediaAssetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProductMediaAsset {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    downloadUri: json["downloadUri"],
    previewUri: json["previewUri"],
    name: json["name"],
    description: json["description"] == null ? undefined : json["description"],
    fileName: json["fileName"] == null ? undefined : json["fileName"],
    contentType: json["contentType"],
    labels: json["labels"],
    createdAt: json["createdAt"] == null ? undefined : json["createdAt"],
    updatedAt: json["updatedAt"] == null ? undefined : json["updatedAt"],
    number: json["number"] == null ? undefined : json["number"],
    attributes:
      json["attributes"] == null
        ? undefined
        : (json["attributes"] as Array<any>).map(AssetAttributeFromJSON),
  };
}

export function ProductMediaAssetToJSON(json: any): ProductMediaAsset {
  return ProductMediaAssetToJSONTyped(json, false);
}

export function ProductMediaAssetToJSONTyped(
  value?: ProductMediaAsset | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    downloadUri: value["downloadUri"],
    previewUri: value["previewUri"],
    name: value["name"],
    description: value["description"],
    fileName: value["fileName"],
    contentType: value["contentType"],
    labels: value["labels"],
    createdAt: value["createdAt"],
    updatedAt: value["updatedAt"],
    number: value["number"],
    attributes:
      value["attributes"] == null
        ? undefined
        : (value["attributes"] as Array<any>).map(AssetAttributeToJSON),
  };
}
