/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProductBundle
 */
export interface ProductBundle {
	/**
	 *
	 * @type {string}
	 * @memberof ProductBundle
	 */
	productId: string;
	/**
	 *
	 * @type {number}
	 * @memberof ProductBundle
	 */
	quantity: number;
}

/**
 * Check if a given object implements the ProductBundle interface.
 */
export function instanceOfProductBundle(value: object): boolean {
	if (!("productId" in value)) return false;
	if (!("quantity" in value)) return false;
	return true;
}

export function ProductBundleFromJSON(json: any): ProductBundle {
	return ProductBundleFromJSONTyped(json, false);
}

export function ProductBundleFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductBundle {
	if (json == null) {
		return json;
	}
	return {
		productId: json["productId"],
		quantity: json["quantity"],
	};
}

export function ProductBundleToJSON(value?: ProductBundle | null): any {
	if (value == null) {
		return value;
	}
	return {
		productId: value["productId"],
		quantity: value["quantity"],
	};
}
