/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Product } from "./Product";
import {
	ProductFromJSON,
	ProductFromJSONTyped,
	ProductToJSON,
	ProductToJSONTyped,
} from "./Product";

/**
 *
 * @export
 * @interface ProductResults
 */
export interface ProductResults {
	/**
	 *
	 * @type {Array<Product>}
	 * @memberof ProductResults
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the ProductResults interface.
 */
export function instanceOfProductResults(
	value: object,
): value is ProductResults {
	if (!("results" in value) || value["results"] === undefined) return false;
	return true;
}

export function ProductResultsFromJSON(json: any): ProductResults {
	return ProductResultsFromJSONTyped(json, false);
}

export function ProductResultsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductResults {
	if (json == null) {
		return json;
	}
	return {
		results: (json["results"] as Array<any>).map(ProductFromJSON),
	};
}

export function ProductResultsToJSON(json: any): ProductResults {
	return ProductResultsToJSONTyped(json, false);
}

export function ProductResultsToJSONTyped(
	value?: ProductResults | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		results: (value["results"] as Array<any>).map(ProductToJSON),
	};
}
