/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Product } from "./Product";
import { ProductFromJSON, ProductToJSON } from "./Product";

/**
 *
 * @export
 * @interface ProductResults
 */
export interface ProductResults {
	/**
	 *
	 * @type {Array<Product>}
	 * @memberof ProductResults
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the ProductResults interface.
 */
export function instanceOfProductResults(value: object): boolean {
	if (!("results" in value)) return false;
	return true;
}

export function ProductResultsFromJSON(json: any): ProductResults {
	return ProductResultsFromJSONTyped(json, false);
}

export function ProductResultsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ProductResults {
	if (json == null) {
		return json;
	}
	return {
		results: (json["results"] as Array<any>).map(ProductFromJSON),
	};
}

export function ProductResultsToJSON(value?: ProductResults | null): any {
	if (value == null) {
		return value;
	}
	return {
		results: (value["results"] as Array<any>).map(ProductToJSON),
	};
}
