/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PublishStateValues = {
	Initializing: "INITIALIZING",
	Pending: "PENDING",
	Publish: "PUBLISH",
	PublishCleanup: "PUBLISH_CLEANUP",
	Closed: "CLOSED",
	Cancelled: "CANCELLED",
} as const;
export type PublishStateValues =
	(typeof PublishStateValues)[keyof typeof PublishStateValues];

export function instanceOfPublishStateValues(value: any): boolean {
	return Object.values(PublishStateValues).includes(value);
}

export function PublishStateValuesFromJSON(json: any): PublishStateValues {
	return PublishStateValuesFromJSONTyped(json, false);
}

export function PublishStateValuesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PublishStateValues {
	return json as PublishStateValues;
}

export function PublishStateValuesToJSON(
	value?: PublishStateValues | null,
): any {
	return value as any;
}
