/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PublishStateValues = {
  Initializing: "INITIALIZING",
  Pending: "PENDING",
  Publish: "PUBLISH",
  PublishCleanup: "PUBLISH_CLEANUP",
  Closed: "CLOSED",
  Cancelled: "CANCELLED",
} as const;
export type PublishStateValues =
  (typeof PublishStateValues)[keyof typeof PublishStateValues];

export function instanceOfPublishStateValues(value: any): boolean {
  for (const key in PublishStateValues) {
    if (Object.prototype.hasOwnProperty.call(PublishStateValues, key)) {
      if (
        PublishStateValues[key as keyof typeof PublishStateValues] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function PublishStateValuesFromJSON(json: any): PublishStateValues {
  return PublishStateValuesFromJSONTyped(json, false);
}

export function PublishStateValuesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PublishStateValues {
  return json as PublishStateValues;
}

export function PublishStateValuesToJSON(
  value?: PublishStateValues | null
): any {
  return value as any;
}

export function PublishStateValuesToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): PublishStateValues {
  return value as PublishStateValues;
}
