/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PublishStateValues } from "./PublishStateValues";
import {
	PublishStateValuesFromJSON,
	PublishStateValuesFromJSONTyped,
	PublishStateValuesToJSON,
	PublishStateValuesToJSONTyped,
} from "./PublishStateValues";

/**
 *
 * @export
 * @interface PublishInfo
 */
export interface PublishInfo {
	/**
	 * mongo identifier of the collection.
	 * @type {string}
	 * @memberof PublishInfo
	 */
	id: string;
	/**
	 *
	 * @type {PublishStateValues}
	 * @memberof PublishInfo
	 */
	state: PublishStateValues;
	/**
	 *
	 * @type {number}
	 * @memberof PublishInfo
	 */
	createdAt: number;
	/**
	 *
	 * @type {number}
	 * @memberof PublishInfo
	 */
	disposedAt?: number;
	/**
	 *
	 * @type {number}
	 * @memberof PublishInfo
	 */
	cleanedAt?: number;
	/**
	 *
	 * @type {string}
	 * @memberof PublishInfo
	 */
	contextId: string;
	/**
	 *
	 * @type {string}
	 * @memberof PublishInfo
	 */
	contextName: string;
}

/**
 * Check if a given object implements the PublishInfo interface.
 */
export function instanceOfPublishInfo(value: object): value is PublishInfo {
	if (!("id" in value) || value["id"] === undefined) return false;
	if (!("state" in value) || value["state"] === undefined) return false;
	if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
	if (!("contextId" in value) || value["contextId"] === undefined) return false;
	if (!("contextName" in value) || value["contextName"] === undefined)
		return false;
	return true;
}

export function PublishInfoFromJSON(json: any): PublishInfo {
	return PublishInfoFromJSONTyped(json, false);
}

export function PublishInfoFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PublishInfo {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		state: PublishStateValuesFromJSON(json["state"]),
		createdAt: json["createdAt"],
		disposedAt: json["disposedAt"] == null ? undefined : json["disposedAt"],
		cleanedAt: json["cleanedAt"] == null ? undefined : json["cleanedAt"],
		contextId: json["contextId"],
		contextName: json["contextName"],
	};
}

export function PublishInfoToJSON(json: any): PublishInfo {
	return PublishInfoToJSONTyped(json, false);
}

export function PublishInfoToJSONTyped(
	value?: PublishInfo | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		state: PublishStateValuesToJSON(value["state"]),
		createdAt: value["createdAt"],
		disposedAt: value["disposedAt"],
		cleanedAt: value["cleanedAt"],
		contextId: value["contextId"],
		contextName: value["contextName"],
	};
}
