/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublishStateValues } from "./PublishStateValues";
import {
	PublishStateValuesFromJSON,
	PublishStateValuesToJSON,
} from "./PublishStateValues";

/**
 *
 * @export
 * @interface PublishInfo
 */
export interface PublishInfo {
	/**
	 * mongo identifier of the collection.
	 * @type {string}
	 * @memberof PublishInfo
	 */
	id: string;
	/**
	 *
	 * @type {PublishStateValues}
	 * @memberof PublishInfo
	 */
	state: PublishStateValues;
	/**
	 *
	 * @type {number}
	 * @memberof PublishInfo
	 */
	createdAt: number;
	/**
	 *
	 * @type {number}
	 * @memberof PublishInfo
	 */
	disposedAt?: number;
	/**
	 *
	 * @type {string}
	 * @memberof PublishInfo
	 */
	contextId: string;
	/**
	 *
	 * @type {string}
	 * @memberof PublishInfo
	 */
	contextName: string;
}

/**
 * Check if a given object implements the PublishInfo interface.
 */
export function instanceOfPublishInfo(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("state" in value)) return false;
	if (!("createdAt" in value)) return false;
	if (!("contextId" in value)) return false;
	if (!("contextName" in value)) return false;
	return true;
}

export function PublishInfoFromJSON(json: any): PublishInfo {
	return PublishInfoFromJSONTyped(json, false);
}

export function PublishInfoFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): PublishInfo {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		state: PublishStateValuesFromJSON(json["state"]),
		createdAt: json["createdAt"],
		disposedAt: json["disposedAt"] == null ? undefined : json["disposedAt"],
		contextId: json["contextId"],
		contextName: json["contextName"],
	};
}

export function PublishInfoToJSON(value?: PublishInfo | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		state: PublishStateValuesToJSON(value["state"]),
		createdAt: value["createdAt"],
		disposedAt: value["disposedAt"],
		contextId: value["contextId"],
		contextName: value["contextName"],
	};
}
