/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RelationDefinition
 */
export interface RelationDefinition {
  /**
   *
   * @type {string}
   * @memberof RelationDefinition
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof RelationDefinition
   */
  number?: string;
  /**
   *
   * @type {string}
   * @memberof RelationDefinition
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RelationDefinition
   */
  reverseName?: string;
  /**
   *
   * @type {number}
   * @memberof RelationDefinition
   */
  order?: number;
}

/**
 * Check if a given object implements the RelationDefinition interface.
 */
export function instanceOfRelationDefinition(
  value: object
): value is RelationDefinition {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function RelationDefinitionFromJSON(json: any): RelationDefinition {
  return RelationDefinitionFromJSONTyped(json, false);
}

export function RelationDefinitionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RelationDefinition {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    number: json["number"] == null ? undefined : json["number"],
    name: json["name"],
    reverseName: json["reverseName"] == null ? undefined : json["reverseName"],
    order: json["order"] == null ? undefined : json["order"],
  };
}

export function RelationDefinitionToJSON(json: any): RelationDefinition {
  return RelationDefinitionToJSONTyped(json, false);
}

export function RelationDefinitionToJSONTyped(
  value?: RelationDefinition | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    number: value["number"],
    name: value["name"],
    reverseName: value["reverseName"],
    order: value["order"],
  };
}
