/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RelatedProductsRelationSortingOrderSource = {
  RelationDefinition: "RELATION_DEFINITION",
  Product: "PRODUCT",
} as const;
export type RelatedProductsRelationSortingOrderSource =
  (typeof RelatedProductsRelationSortingOrderSource)[keyof typeof RelatedProductsRelationSortingOrderSource];

export function instanceOfRelatedProductsRelationSortingOrderSource(
  value: any
): boolean {
  for (const key in RelatedProductsRelationSortingOrderSource) {
    if (
      Object.prototype.hasOwnProperty.call(
        RelatedProductsRelationSortingOrderSource,
        key
      )
    ) {
      if (
        RelatedProductsRelationSortingOrderSource[
          key as keyof typeof RelatedProductsRelationSortingOrderSource
        ] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function RelatedProductsRelationSortingOrderSourceFromJSON(
  json: any
): RelatedProductsRelationSortingOrderSource {
  return RelatedProductsRelationSortingOrderSourceFromJSONTyped(json, false);
}

export function RelatedProductsRelationSortingOrderSourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RelatedProductsRelationSortingOrderSource {
  return json as RelatedProductsRelationSortingOrderSource;
}

export function RelatedProductsRelationSortingOrderSourceToJSON(
  value?: RelatedProductsRelationSortingOrderSource | null
): any {
  return value as any;
}

export function RelatedProductsRelationSortingOrderSourceToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): RelatedProductsRelationSortingOrderSource {
  return value as RelatedProductsRelationSortingOrderSource;
}
