/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RelationDirection = {
  OneWay: "ONE_WAY",
  TwoWay: "TWO_WAY",
} as const;
export type RelationDirection =
  (typeof RelationDirection)[keyof typeof RelationDirection];

export function instanceOfRelationDirection(value: any): boolean {
  for (const key in RelationDirection) {
    if (Object.prototype.hasOwnProperty.call(RelationDirection, key)) {
      if (RelationDirection[key as keyof typeof RelationDirection] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RelationDirectionFromJSON(json: any): RelationDirection {
  return RelationDirectionFromJSONTyped(json, false);
}

export function RelationDirectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RelationDirection {
  return json as RelationDirection;
}

export function RelationDirectionToJSON(value?: RelationDirection | null): any {
  return value as any;
}

export function RelationDirectionToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): RelationDirection {
  return value as RelationDirection;
}
