/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RelationDirection = {
	OneWay: "ONE_WAY",
	TwoWay: "TWO_WAY",
} as const;
export type RelationDirection =
	(typeof RelationDirection)[keyof typeof RelationDirection];

export function instanceOfRelationDirection(value: any): boolean {
	return Object.values(RelationDirection).includes(value);
}

export function RelationDirectionFromJSON(json: any): RelationDirection {
	return RelationDirectionFromJSONTyped(json, false);
}

export function RelationDirectionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RelationDirection {
	return json as RelationDirection;
}

export function RelationDirectionToJSON(value?: RelationDirection | null): any {
	return value as any;
}
