/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RelationDefinition
 */
export interface RelationDefinition {
	/**
	 *
	 * @type {string}
	 * @memberof RelationDefinition
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof RelationDefinition
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RelationDefinition
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof RelationDefinition
	 */
	reverseName?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RelationDefinition
	 */
	order?: number;
}

/**
 * Check if a given object implements the RelationDefinition interface.
 */
export function instanceOfRelationDefinition(value: object): boolean {
	if (!("id" in value)) return false;
	if (!("name" in value)) return false;
	return true;
}

export function RelationDefinitionFromJSON(json: any): RelationDefinition {
	return RelationDefinitionFromJSONTyped(json, false);
}

export function RelationDefinitionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RelationDefinition {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		number: json["number"] == null ? undefined : json["number"],
		name: json["name"],
		reverseName: json["reverseName"] == null ? undefined : json["reverseName"],
		order: json["order"] == null ? undefined : json["order"],
	};
}

export function RelationDefinitionToJSON(
	value?: RelationDefinition | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		number: value["number"],
		name: value["name"],
		reverseName: value["reverseName"],
		order: value["order"],
	};
}
