/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RelatedProductsRelationSortingOrderSource = {
	RelationDefinition: "RELATION_DEFINITION",
	Product: "PRODUCT",
} as const;
export type RelatedProductsRelationSortingOrderSource =
	(typeof RelatedProductsRelationSortingOrderSource)[keyof typeof RelatedProductsRelationSortingOrderSource];

export function instanceOfRelatedProductsRelationSortingOrderSource(
	value: any,
): boolean {
	return Object.values(RelatedProductsRelationSortingOrderSource).includes(
		value,
	);
}

export function RelatedProductsRelationSortingOrderSourceFromJSON(
	json: any,
): RelatedProductsRelationSortingOrderSource {
	return RelatedProductsRelationSortingOrderSourceFromJSONTyped(json, false);
}

export function RelatedProductsRelationSortingOrderSourceFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RelatedProductsRelationSortingOrderSource {
	return json as RelatedProductsRelationSortingOrderSource;
}

export function RelatedProductsRelationSortingOrderSourceToJSON(
	value?: RelatedProductsRelationSortingOrderSource | null,
): any {
	return value as any;
}
