/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RowAttributeDefinitionValue
 */
export interface RowAttributeDefinitionValue {
  /**
   *
   * @type {string}
   * @memberof RowAttributeDefinitionValue
   */
  valueId: string;
  /**
   *
   * @type {string}
   * @memberof RowAttributeDefinitionValue
   */
  value?: string;
}

/**
 * Check if a given object implements the RowAttributeDefinitionValue interface.
 */
export function instanceOfRowAttributeDefinitionValue(
  value: object
): value is RowAttributeDefinitionValue {
  if (!("valueId" in value) || value["valueId"] === undefined) return false;
  return true;
}

export function RowAttributeDefinitionValueFromJSON(
  json: any
): RowAttributeDefinitionValue {
  return RowAttributeDefinitionValueFromJSONTyped(json, false);
}

export function RowAttributeDefinitionValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RowAttributeDefinitionValue {
  if (json == null) {
    return json;
  }
  return {
    valueId: json["valueId"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function RowAttributeDefinitionValueToJSON(
  json: any
): RowAttributeDefinitionValue {
  return RowAttributeDefinitionValueToJSONTyped(json, false);
}

export function RowAttributeDefinitionValueToJSONTyped(
  value?: RowAttributeDefinitionValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    valueId: value["valueId"],
    value: value["value"],
  };
}
