/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RowAttributeDefinitionValue
 */
export interface RowAttributeDefinitionValue {
	/**
	 *
	 * @type {string}
	 * @memberof RowAttributeDefinitionValue
	 */
	valueId: string;
	/**
	 *
	 * @type {string}
	 * @memberof RowAttributeDefinitionValue
	 */
	value?: string;
}

/**
 * Check if a given object implements the RowAttributeDefinitionValue interface.
 */
export function instanceOfRowAttributeDefinitionValue(value: object): boolean {
	if (!("valueId" in value)) return false;
	return true;
}

export function RowAttributeDefinitionValueFromJSON(
	json: any,
): RowAttributeDefinitionValue {
	return RowAttributeDefinitionValueFromJSONTyped(json, false);
}

export function RowAttributeDefinitionValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RowAttributeDefinitionValue {
	if (json == null) {
		return json;
	}
	return {
		valueId: json["valueId"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function RowAttributeDefinitionValueToJSON(
	value?: RowAttributeDefinitionValue | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		valueId: value["valueId"],
		value: value["value"],
	};
}
