/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SegmentContextRequest
 */
export interface SegmentContextRequest {
  /**
   * Context id, or 'en' if id is not specified.
   * @type {string}
   * @memberof SegmentContextRequest
   */
  context?: string;
  /**
   * Context name, or 'default' if name is not specified.
   * @type {string}
   * @memberof SegmentContextRequest
   */
  contextName?: string;
}

/**
 * Check if a given object implements the SegmentContextRequest interface.
 */
export function instanceOfSegmentContextRequest(
  value: object
): value is SegmentContextRequest {
  return true;
}

export function SegmentContextRequestFromJSON(
  json: any
): SegmentContextRequest {
  return SegmentContextRequestFromJSONTyped(json, false);
}

export function SegmentContextRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SegmentContextRequest {
  if (json == null) {
    return json;
  }
  return {
    context: json["context"] == null ? undefined : json["context"],
    contextName: json["contextName"] == null ? undefined : json["contextName"],
  };
}

export function SegmentContextRequestToJSON(json: any): SegmentContextRequest {
  return SegmentContextRequestToJSONTyped(json, false);
}

export function SegmentContextRequestToJSONTyped(
  value?: SegmentContextRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    context: value["context"],
    contextName: value["contextName"],
  };
}
