/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SegmentContextRequest
 */
export interface SegmentContextRequest {
	/**
	 * Context id, or 'en' if id is not specified.
	 * @type {string}
	 * @memberof SegmentContextRequest
	 */
	context?: string;
	/**
	 * Context name, or 'default' if name is not specified.
	 * @type {string}
	 * @memberof SegmentContextRequest
	 */
	contextName?: string;
}

/**
 * Check if a given object implements the SegmentContextRequest interface.
 */
export function instanceOfSegmentContextRequest(value: object): boolean {
	return true;
}

export function SegmentContextRequestFromJSON(
	json: any,
): SegmentContextRequest {
	return SegmentContextRequestFromJSONTyped(json, false);
}

export function SegmentContextRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): SegmentContextRequest {
	if (json == null) {
		return json;
	}
	return {
		context: json["context"] == null ? undefined : json["context"],
		contextName: json["contextName"] == null ? undefined : json["contextName"],
	};
}

export function SegmentContextRequestToJSON(
	value?: SegmentContextRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		context: value["context"],
		contextName: value["contextName"],
	};
}
