/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SelectValue
 */
export interface SelectValue {
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	value?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	metadata?: string;
}

/**
 * Check if a given object implements the SelectValue interface.
 */
export function instanceOfSelectValue(value: object): boolean {
	if (!("id" in value)) return false;
	return true;
}

export function SelectValueFromJSON(json: any): SelectValue {
	return SelectValueFromJSONTyped(json, false);
}

export function SelectValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): SelectValue {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
		metadata: json["metadata"] == null ? undefined : json["metadata"],
	};
}

export function SelectValueToJSON(value?: SelectValue | null): any {
	if (value == null) {
		return value;
	}
	return {
		id: value["id"],
		number: value["number"],
		value: value["value"],
		metadata: value["metadata"],
	};
}
