/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SelectValue
 */
export interface SelectValue {
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	value?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectValue
	 */
	metadata?: string;
}

/**
 * Check if a given object implements the SelectValue interface.
 */
export function instanceOfSelectValue(value: object): value is SelectValue {
	if (!("id" in value) || value["id"] === undefined) return false;
	return true;
}

export function SelectValueFromJSON(json: any): SelectValue {
	return SelectValueFromJSONTyped(json, false);
}

export function SelectValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): SelectValue {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"],
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
		metadata: json["metadata"] == null ? undefined : json["metadata"],
	};
}

export function SelectValueToJSON(json: any): SelectValue {
	return SelectValueToJSONTyped(json, false);
}

export function SelectValueToJSONTyped(
	value?: SelectValue | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		number: value["number"],
		value: value["value"],
		metadata: value["metadata"],
	};
}
