/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API  <b><h1>Deprecated endpoints:</h1></b><table border=\"1px;\"><tr><th style=\"text-align: center; vertical-align: middle;\"><b><h3>Uri</b></h3></th><th><b>Method</b></th><th><b><h3>Since</h3></b></th><th><b><h3>End of life</h3></b></th></tr></table>
 *
 * The version of the OpenAPI document: 1-core
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StatusPapiError
 */
export interface StatusPapiError {
  /**
   *
   * @type {number}
   * @memberof StatusPapiError
   */
  status: number;
  /**
   *
   * @type {string}
   * @memberof StatusPapiError
   */
  message: string;
}

/**
 * Check if a given object implements the StatusPapiError interface.
 */
export function instanceOfStatusPapiError(
  value: object
): value is StatusPapiError {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function StatusPapiErrorFromJSON(json: any): StatusPapiError {
  return StatusPapiErrorFromJSONTyped(json, false);
}

export function StatusPapiErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StatusPapiError {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    message: json["message"],
  };
}

export function StatusPapiErrorToJSON(json: any): StatusPapiError {
  return StatusPapiErrorToJSONTyped(json, false);
}

export function StatusPapiErrorToJSONTyped(
  value?: StatusPapiError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    message: value["message"],
  };
}
