/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StatusPapiError
 */
export interface StatusPapiError {
	/**
	 *
	 * @type {number}
	 * @memberof StatusPapiError
	 */
	status: number;
	/**
	 *
	 * @type {string}
	 * @memberof StatusPapiError
	 */
	message: string;
}

/**
 * Check if a given object implements the StatusPapiError interface.
 */
export function instanceOfStatusPapiError(value: object): boolean {
	if (!("status" in value)) return false;
	if (!("message" in value)) return false;
	return true;
}

export function StatusPapiErrorFromJSON(json: any): StatusPapiError {
	return StatusPapiErrorFromJSONTyped(json, false);
}

export function StatusPapiErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): StatusPapiError {
	if (json == null) {
		return json;
	}
	return {
		status: json["status"],
		message: json["message"],
	};
}

export function StatusPapiErrorToJSON(value?: StatusPapiError | null): any {
	if (value == null) {
		return value;
	}
	return {
		status: value["status"],
		message: value["message"],
	};
}
