/* tslint:disable */
/* eslint-disable */
/**
 *
 * Bluestone Public API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ValueAttributeDefinitionValue
 */
export interface ValueAttributeDefinitionValue {
	/**
	 *
	 * @type {string}
	 * @memberof ValueAttributeDefinitionValue
	 */
	valueId: string;
	/**
	 *
	 * @type {string}
	 * @memberof ValueAttributeDefinitionValue
	 */
	number?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ValueAttributeDefinitionValue
	 */
	value?: string;
}

/**
 * Check if a given object implements the ValueAttributeDefinitionValue interface.
 */
export function instanceOfValueAttributeDefinitionValue(
	value: object,
): boolean {
	if (!("valueId" in value)) return false;
	return true;
}

export function ValueAttributeDefinitionValueFromJSON(
	json: any,
): ValueAttributeDefinitionValue {
	return ValueAttributeDefinitionValueFromJSONTyped(json, false);
}

export function ValueAttributeDefinitionValueFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ValueAttributeDefinitionValue {
	if (json == null) {
		return json;
	}
	return {
		valueId: json["valueId"],
		number: json["number"] == null ? undefined : json["number"],
		value: json["value"] == null ? undefined : json["value"],
	};
}

export function ValueAttributeDefinitionValueToJSON(
	value?: ValueAttributeDefinitionValue | null,
): any {
	if (value == null) {
		return value;
	}
	return {
		valueId: value["valueId"],
		number: value["number"],
		value: value["value"],
	};
}
